Q.Places.countries = [
    ["Afghánistán","AF"],
    ["Alandy","AX"],
    ["Albánie","AL"],
    ["Alžírsko","DZ"],
    ["Americká Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antigua a Barbuda","AG"],
    ["Argentina","AR"],
    ["Arménie","AM"],
    ["Aruba","AW"],
    ["Austrálie","AU"],
    ["Rakousko","AT"],
    ["Ázerbájdžán","AZ"],
    ["Bahamy","BS"],
    ["Bahrajn","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Bělorusko","BY"],
    ["Belgie","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhútán","BT"],
    ["Bolívie, Mnohonárodní stát","BO"],
    ["Bonaire, Sint Eustatius a Saba","BQ"],
    ["Bosna a Hercegovina","BA"],
    ["Botswana","BW"],
    ["Bouvetův ostrov","BV"],
    ["Brazílie","BR"],
    ["Britské indickooceánské území","IO"],
    ["Brunej","BN"],
    ["Bulharsko","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambodža","KH"],
    ["Kamerun","CM"],
    ["Kanada","CA"],
    ["Kapverdy","CV"],
    ["Kajmanské ostrovy","KY"],
    ["Středoafrická republika","CF"],
    ["Chad","TD"],
    ["Chile","CL"],
    ["Čína","CN"],
    ["Vánoční ostrov","CX"],
    ["Kokosové ostrovy (Keeling)","CC"],
    ["Colombia","CO"],
    ["Komory","KM"],
    ["Congo","CG"],
    ["Kongo, demokratická republika","CD"],
    ["Cookovy ostrovy","CK"],
    ["Costa Rica","CR"],
    ["Pobřeží slonoviny","CI"],
    ["Chorvatsko","HR"],
    ["Kuba","CU"],
    ["Curaçao","CW"],
    ["Kypr","CY"],
    ["Česká republika","CZ"],
    ["Dánsko","DK"],
    ["Djibouti","DJ"],
    ["Dominika","DM"],
    ["Dominikánská republika","DO"],
    ["Ecuador","EC"],
    ["Egypt","EG"],
    ["El Salvador","SV"],
    ["Rovníková Guinea","GQ"],
    ["Eritrea","ER"],
    ["Estonsko","EE"],
    ["Etiopie","ET"],
    ["Falklandy (Malvíny)","FK"],
    ["Faerské ostrovy","FO"],
    ["Fidži","FJ"],
    ["Finsko","FI"],
    ["Francie","FR"],
    ["Francouzská Guyana","GF"],
    ["Francouzská Polynésie","PF"],
    ["Francouzská jižní teritoria","TF"],
    ["Gabon","GA"],
    ["Gambie","GM"],
    ["Georgia","GE"],
    ["Německo","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Řecko","GR"],
    ["Grónsko","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Heard ostrov a McDonald ostrovy","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Maďarsko","HU"],
    ["Island","IS"],
    ["Indie","IN"],
    ["Indonesia","ID"],
    ["Iran, Islamic Republic of","IR"],
    ["Irák","IQ"],
    ["Ireland","IE"],
    ["Isle of Man","IM"],
    ["Izrael","IL"],
    ["Itálie","IT"],
    ["Jamaica","JM"],
    ["Japan","JP"],
    ["Jersey","JE"],
    ["Jordán","JO"],
    ["Kazachstán","KZ"],
    ["Keni","KE"],
    ["Kiribati","KI"],
    ["Korejská lidová republika","KP"],
    ["Korejská republika","KR"],
    ["Kuwait","KW"],
    ["Kyrgyzstán","KG"],
    ["Lao lidová demokratická republika","LA"],
    ["Latvia","LV"],
    ["Libanon","LB"],
    ["Lesotho","LS"],
    ["Libérie","LR"],
    ["Libye","LY"],
    ["Lichtenštejnsko","LI"],
    ["Litva","LT"],
    ["Luxembourg","LU"],
    ["Macao","MO"],
    ["Makedonii","MK"],
    ["Madagaskar","MG"],
    ["Malawi","MW"],
    ["Malajsie","MY"],
    ["Maledivy","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshallovy ostrovy","MH"],
    ["Martinique","MQ"],
    ["Mauritánie","MR"],
    ["Mauricius","MU"],
    ["Mayotte","YT"],
    ["Mexiko","MX"],
    ["Mikronésie, Federativní státy","FM"],
    ["Moldavská republika","MD"],
    ["Monaco","MC"],
    ["Mongolsko","MN"],
    ["Černá Hora","ME"],
    ["Montserrat","MS"],
    ["Maroko","MA"],
    ["Mosambik","MZ"],
    ["Myanmar","MM"],
    ["Namibie","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Nizozemsko","NL"],
    ["Nová Kaledonie","NC"],
    ["New Zealand","NZ"],
    ["Nikaragua","NI"],
    ["Niger","NE"],
    ["Nigérie","NG"],
    ["Niue","NU"],
    ["Norfolk","NF"],
    ["Severní Mariany","MP"],
    ["Norsko","NO"],
    ["Omán","OM"],
    ["Pákistán","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panama","PA"],
    ["Papua-Nová Guinea","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Filipíny","PH"],
    ["Pitcairn","PN"],
    ["Polsko","PL"],
    ["Portugalsko","PT"],
    ["Puerto Rico","PR"],
    ["Katar","QA"],
    ["Réunion","RE"],
    ["Rumunsko","RO"],
    ["Ruská federace","RU"],
    ["Rwanda","RW"],
    ["Svatý Bartoloměj","BL"],
    ["Svatá Helena a Tristan da Cunha","SH"],
    ["Svatý Kryštof a Nevis","KN"],
    ["Svatá Lucie","LC"],
    ["Svatý Martin (francouzská část)","MF"],
    ["Saint-Pierre a Miquelon","PM"],
    ["Svatý Vincenc a Grenadiny","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Svatý Tomáš a Princův","ST"],
    ["Saúdská Arábie","SA"],
    ["Senegal","SN"],
    ["Srbsko","RS"],
    ["Seychely","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (holandský část)","SX"],
    ["Slovensko","SK"],
    ["Slovenia","SI"],
    ["Šalamounovy ostrovy","SB"],
    ["Somálsko","SO"],
    ["South Africa","ZA"],
    ["South Georgia","GS"],
    ["Jižní Súdán","SS"],
    ["Španělsko","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Surinam","SR"],
    ["Špicberky a Jan Mayen","SJ"],
    ["Svazijsko","SZ"],
    ["Švédsko","SE"],
    ["Švýcarsko","CH"],
    ["Syrská arabská republika","SY"],
    ["Taiwan, provincie Číny","TW"],
    ["Tádžikistán","TJ"],
    ["Tanzanie, Sjednocená republika","TZ"],
    ["Thailand","TH"],
    ["Východní Timor","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad a Tobago","TT"],
    ["Tunisko","TN"],
    ["Turkey","TR"],
    ["Turkmenistán","TM"],
    ["Turks a Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukrajina","UA"],
    ["Spojené arabské emiráty","AE"],
    ["Spojené království","GB"],
    ["Spojené státy","US"],
    ["Menší odlehlé ostrovy Spojených států amerických","UM"],
    ["Uruguay","UY"],
    ["Uzbekistán","UZ"],
    ["Vanuatu","VU"],
    ["Vatikán","VA"],
    ["Venezuela, Bolívarovská republika","VE"],
    ["Viet Nam","VN"],
    ["Panenské ostrovy, Britské","VG"],
    ["Panenské ostrovy, na území USA.","VI"],
    ["Wallis a Futuna","WF"],
    ["Západní Sahara","EH"],
    ["Jemen","YE"],
    ["Zambie","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}