Q.Places.countries = [
    ["Afganistan","AF"],
    ["Ahvenamaa","AX"],
    ["Albaania","AL"],
    ["Alžeeria","DZ"],
    ["Ameerika Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarktika","AQ"],
    ["Antigua ja Barbuda","AG"],
    ["Argentina","AR"],
    ["Armeenia","AM"],
    ["Aruba","AW"],
    ["Austraalia","AU"],
    ["Austria","AT"],
    ["Aserbaidžaan","AZ"],
    ["Bahama","BS"],
    ["Bahrein","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Valgevene","BY"],
    ["Belgia","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Boliivia Paljurahvuseline Riik","BO"],
    ["Bonaire, Sint Eustatius ja Saba","BQ"],
    ["Bosnia ja Hertsegoviina","BA"],
    ["Botswana","BW"],
    ["Bouvet saar","BV"],
    ["Brasiilia","BR"],
    ["Briti India ookeani ala","IO"],
    ["Brunei","BN"],
    ["Bulgaaria","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambodža","KH"],
    ["Kamerun","CM"],
    ["Kanada","CA"],
    ["Cabo Verde","CV"],
    ["Kaimanisaared","KY"],
    ["Kesk-Aafrika Vabariik","CF"],
    ["Chad","TD"],
    ["Tšiili","CL"],
    ["Hiinas","CN"],
    ["Jõulusaar","CX"],
    ["Kookossaared (Keeling) Islands","CC"],
    ["Colombia","CO"],
    ["Komoorid","KM"],
    ["Congo","CG"],
    ["Kongo Demokraatlik Vabariik","CD"],
    ["Cook Islands","CK"],
    ["Costa Rica","CR"],
    ["Côte d'Ivoire","CI"],
    ["Horvaatia","HR"],
    ["Kuuba","CU"],
    ["Curaçao","CW"],
    ["Küpros","CY"],
    ["Tšehhi Vabariik","CZ"],
    ["Taani","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Dominikaani Vabariik","DO"],
    ["Ecuador","EC"],
    ["Egiptus","EG"],
    ["El Salvador","SV"],
    ["Ekvatoriaal-Guinea","GQ"],
    ["Eritrea","ER"],
    ["Estonia","EE"],
    ["Etioopia","ET"],
    ["Falklandi saared (Malvinas)","FK"],
    ["Fääri saared","FO"],
    ["Fidži","FJ"],
    ["Soome","FI"],
    ["Prantsusmaa","FR"],
    ["Prantsuse Guajaana","GF"],
    ["Prantsuse Polüneesia","PF"],
    ["Prantsuse Lõunaalad","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Saksamaa","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Kreeka","GR"],
    ["Gröönimaa","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guami","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Heard ja McDonald","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Ungari","HU"],
    ["Island","IS"],
    ["India","IN"],
    ["Indoneesia","ID"],
    ["Iran, Islamic Republic of","IR"],
    ["Iraak","IQ"],
    ["Iirimaa","IE"],
    ["Isle of Man","IM"],
    ["Iisrael","IL"],
    ["Itaalia","IT"],
    ["Jamaica","JM"],
    ["Jaapan","JP"],
    ["Jersey","JE"],
    ["Jordaania","JO"],
    ["Kasahstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Korea Rahvademokraatlik Vabariik","KP"],
    ["Lõuna-Korea","KR"],
    ["Kuveit","KW"],
    ["Kõrgõzstan","KG"],
    ["Laose Demokraatlik Vabariik","LA"],
    ["Läti","LV"],
    ["Liibanon","LB"],
    ["Lesotho","LS"],
    ["Libeeria","LR"],
    ["Liibüa","LY"],
    ["Liechtenstein","LI"],
    ["Leedu","LT"],
    ["Luksemburg","LU"],
    ["Macao","MO"],
    ["Makedoonia","MK"],
    ["Madagaskar","MG"],
    ["Malawi","MW"],
    ["Malaisia","MY"],
    ["Maldiivid","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshalli Saared","MH"],
    ["Martinique","MQ"],
    ["Mauritaania","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mehhiko","MX"],
    ["Mikroneesia Liiduriigid","FM"],
    ["Moldova Vabariik","MD"],
    ["Monaco","MC"],
    ["Mongoolia","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Maroko","MA"],
    ["Mosambiik","MZ"],
    ["Myanmar","MM"],
    ["Namiibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Holland","NL"],
    ["New Caledonia","NC"],
    ["Uus-Meremaa","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeeria","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Põhja-Mariaanid","MP"],
    ["Norra","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestiina","PS"],
    ["Panama","PA"],
    ["Paapua Uus-Guinea","PG"],
    ["Paraguays","PY"],
    ["Peruu","PE"],
    ["Filipiinid","PH"],
    ["Pitcairn","PN"],
    ["Poola","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Katar","QA"],
    ["Réunion","RE"],
    ["Rumeenia","RO"],
    ["Venemaa","RU"],
    ["Rwanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena ja Tristan da Cunha","SH"],
    ["Saint Kitts ja Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint-Martin (Prantsuse osa)","MF"],
    ["Saint-Pierre ja Miquelon","PM"],
    ["Saint Vincent ja Grenadiinid","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome ja Principe","ST"],
    ["Saudi Araabia","SA"],
    ["Senegal","SN"],
    ["Serbia","RS"],
    ["Seišellid","SC"],
    ["Sierra Leone","SL"],
    ["Singapur","SG"],
    ["Sint Maarten (Hollandi osa)","SX"],
    ["Slovakkia","SK"],
    ["Sloveenia","SI"],
    ["Saalomoni Saared","SB"],
    ["Somaalia","SO"],
    ["Lõuna-Aafrika","ZA"],
    ["Lõuna-Georgia","GS"],
    ["Lõuna-Sudaan","SS"],
    ["Hispaania","ES"],
    ["Sri Lanka","LK"],
    ["Sudaan","SD"],
    ["Suriname","SR"],
    ["Svalbard ja Jan Mayen","SJ"],
    ["Svaasimaa","SZ"],
    ["Rootsi","SE"],
    ["Šveits","CH"],
    ["Süüria","SY"],
    ["Taiwan, Hiina provints","TW"],
    ["Tadžikistan","TJ"],
    ["Tansaania kohta","TZ"],
    ["Tai","TH"],
    ["Ida-Timor","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad ja Tobago","TT"],
    ["Tuneesia","TN"],
    ["Türgi","TR"],
    ["Türkmenistan","TM"],
    ["Turks ja Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraina","UA"],
    ["Araabia Ühendemiraadid","AE"],
    ["Ühendkuningriik","GB"],
    ["Ameerika Ühendriigid","US"],
    ["USA hajasaared","UM"],
    ["Uruguay","UY"],
    ["Usbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatikan","VA"],
    ["Venezuela Bolivari Vabariik","VE"],
    ["Vietnami","VN"],
    ["Neitsisaared, Briti","VG"],
    ["Neitsisaared, USA-s.","VI"],
    ["Wallis ja Futuna","WF"],
    ["Lääne-Sahara","EH"],
    ["Jeemenis","YE"],
    ["Sambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}