Q.Places.countries = [
    ["Afganistan","AF"],
    ["Ahvenanmaa","AX"],
    ["Albania","AL"],
    ["Algeria","DZ"],
    ["Amerikan Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarktis","AQ"],
    ["Antigua ja Barbuda","AG"],
    ["Argentiina","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Itävalta","AT"],
    ["Azerbaidžan","AZ"],
    ["Bahama","BS"],
    ["Bahrain","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Valko-Venäjä","BY"],
    ["Belgia","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Bolivia on","BO"],
    ["Bonaire, Sint Eustatius ja Saba","BQ"],
    ["Bosnia ja Hertsegovina","BA"],
    ["Botswana","BW"],
    ["Bouvet'nsaari","BV"],
    ["Brazil","BR"],
    ["Brittiläinen Intian valtameren alue","IO"],
    ["Brunei","BN"],
    ["Bulgaria","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambodža","KH"],
    ["Kamerun","CM"],
    ["Kanada","CA"],
    ["Kap Verde","CV"],
    ["Caymansaaret","KY"],
    ["Keski-Afrikkalainen tasavalta","CF"],
    ["Chad","TD"],
    ["Chile","CL"],
    ["Kiina","CN"],
    ["Joulusaari","CX"],
    ["Cocos (Keeling) Islands","CC"],
    ["Kolumbia","CO"],
    ["Komorit","KM"],
    ["Congo","CG"],
    ["Kongon demokraattinen tasavalta","CD"],
    ["Cook Islands","CK"],
    ["Costa Rica","CR"],
    ["Norsunluurannikko","CI"],
    ["Kroatia","HR"],
    ["Kuuba","CU"],
    ["Curaçao","CW"],
    ["Kypros","CY"],
    ["Tšekki","CZ"],
    ["Tanska","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Dominikaaninen tasavalta","DO"],
    ["Ecuador","EC"],
    ["Egypti","EG"],
    ["El Salvadorin","SV"],
    ["Päiväntasaajan Guinea","GQ"],
    ["Eritrea","ER"],
    ["Viro","EE"],
    ["Etiopia","ET"],
    ["Falklandin saaret (Malvinas)","FK"],
    ["Färsaaret","FO"],
    ["Fiji","FJ"],
    ["Suomi","FI"],
    ["France","FR"],
    ["Ranskan Guayana","GF"],
    ["Ranskan Polynesian","PF"],
    ["Ranskan eteläiset alueet","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Saksa","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Kreikka","GR"],
    ["Grönlanti","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Heard ja McDonald Islands","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Unkari","HU"],
    ["Islanti","IS"],
    ["Intia","IN"],
    ["Indonesia","ID"],
    ["Iranin islamilainen tasavalta","IR"],
    ["Irak","IQ"],
    ["Ireland","IE"],
    ["Isle of Man","IM"],
    ["Israel","IL"],
    ["Italia","IT"],
    ["Jamaika","JM"],
    ["Japan","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazakstan","KZ"],
    ["Kenia","KE"],
    ["Kiribati","KI"],
    ["Korean demokraattinen kansantasavalta","KP"],
    ["Korean tasavalta","KR"],
    ["Kuwait","KW"],
    ["Kirgisia","KG"],
    ["Lao People's Democratic Republic","LA"],
    ["Latvia","LV"],
    ["Libanon","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libya","LY"],
    ["Liechtenstein","LI"],
    ["Liettua","LT"],
    ["Luxemburg","LU"],
    ["Macao","MO"],
    ["Makedonia","MK"],
    ["Madagaskar","MG"],
    ["Malawi","MW"],
    ["Malesia","MY"],
    ["Malediivit","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshallinsaaret","MH"],
    ["Martinique","MQ"],
    ["Mauritania","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Meksiko","MX"],
    ["Mikronesia of","FM"],
    ["Moldova","MD"],
    ["Monaco","MC"],
    ["Mongolia","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Marokko","MA"],
    ["Mosambik","MZ"],
    ["Myanmar","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Alankomaat","NL"],
    ["Uudessa-Kaledoniassa","NC"],
    ["Uusi-Seelanti","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Norfolkinsaari","NF"],
    ["Pohjois-Mariaanien","MP"],
    ["Norja","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestiina","PS"],
    ["Panama","PA"],
    ["Papua","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Filippiinit","PH"],
    ["Pitcairn","PN"],
    ["Puola","PL"],
    ["Portugali","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Réunion","RE"],
    ["Romania","RO"],
    ["Venäjä","RU"],
    ["Ruanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena ja Tristan da Cunha","SH"],
    ["Saint Kitts ja Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (ranskalainen osa)","MF"],
    ["Saint-Pierre ja Miquelon","PM"],
    ["Saint Vincent ja Grenadiinit","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome ja Principe","ST"],
    ["Saudi-Arabia","SA"],
    ["Senegal","SN"],
    ["Serbia","RS"],
    ["Seychellit","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (Dutch osa)","SX"],
    ["Slovakia","SK"],
    ["Slovenia","SI"],
    ["Salomonsaaret","SB"],
    ["Somalia","SO"],
    ["Etelä-Afrikka","ZA"],
    ["South Georgia","GS"],
    ["Etelä-Sudan","SS"],
    ["Espanja","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Suriname","SR"],
    ["Huippuvuoret","SJ"],
    ["Swazimaa","SZ"],
    ["Ruotsi","SE"],
    ["Sveitsi","CH"],
    ["Syyria","SY"],
    ["Taiwan, Kiinan maakunta","TW"],
    ["Tadžikistan","TJ"],
    ["Tansania of","TZ"],
    ["Thaimaa","TH"],
    ["Itä-Timor","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad ja Tobago","TT"],
    ["Tunisia","TN"],
    ["Turkki","TR"],
    ["Turkmenistan","TM"],
    ["Turks- ja Caicossaaret","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraina","UA"],
    ["Arabiemiirikunnat","AE"],
    ["Iso-Britannia","GB"],
    ["United States","US"],
    ["United States pienet erillissaaret","UM"],
    ["Uruguay","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatikaanivaltion","VA"],
    ["Venezuela of","VE"],
    ["Vietnam","VN"],
    ["Brittiläiset Neitsytsaaret","VG"],
    ["Neitsytsaaret US-.","VI"],
    ["Wallis ja Futunassa","WF"],
    ["Länsi-Sahara","EH"],
    ["Jemen","YE"],
    ["Sambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}