Q.Places.countries = [
    ["Afghanistan","AF"],
    ["Îles Åland","AX"],
    ["Albanie","AL"],
    ["Algérie","DZ"],
    ["American Samoa","AS"],
    ["Andorre","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antigua-et-Barbuda","AG"],
    ["Argentina","AR"],
    ["Arménie","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Austria","AT"],
    ["Azerbaïdjan","AZ"],
    ["Bahamas","BS"],
    ["Bahreïn","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Belarus","BY"],
    ["Belgique","BE"],
    ["Belize","BZ"],
    ["Bénin","BJ"],
    ["Bermudes","BM"],
    ["Bhoutan","BT"],
    ["Bolivie, Etat plurinational de","BO"],
    ["Bonaire, Sint Eustatius et Saba","BQ"],
    ["Bosnie-Herzégovine","BA"],
    ["Botswana","BW"],
    ["Île Bouvet","BV"],
    ["Brazil","BR"],
    ["Territoire britannique de l'océan Indien","IO"],
    ["Brunei Darussalam","BN"],
    ["Bulgaria","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Cambodia","KH"],
    ["Cameroun","CM"],
    ["Canada","CA"],
    ["Cap-Vert","CV"],
    ["Îles Caïmans","KY"],
    ["République centrafricaine","CF"],
    ["Tchad","TD"],
    ["Chili","CL"],
    ["Chine","CN"],
    ["Christmas Island","CX"],
    ["Cocos (Keeling)","CC"],
    ["Colombie","CO"],
    ["Comores","KM"],
    ["Congo","CG"],
    ["Congo, la République démocratique du","CD"],
    ["Îles Cook","CK"],
    ["Costa Rica","CR"],
    ["Côte d'Ivoire","CI"],
    ["Croatie","HR"],
    ["Cuba","CU"],
    ["Curaçao","CW"],
    ["Chypre","CY"],
    ["République tchèque","CZ"],
    ["Danemark","DK"],
    ["Djibouti","DJ"],
    ["Dominique","DM"],
    ["République dominicaine","DO"],
    ["Equateur","EC"],
    ["Egypte","EG"],
    ["El Salvador","SV"],
    ["Guinée équatoriale","GQ"],
    ["Erythrée","ER"],
    ["Estonie","EE"],
    ["Ethiopie","ET"],
    ["Îles Falkland (Malvinas)","FK"],
    ["Îles Féroé","FO"],
    ["Fidji","FJ"],
    ["Finlande","FI"],
    ["France","FR"],
    ["Guyane française","GF"],
    ["Polynésie française","PF"],
    ["Terres australes françaises","TF"],
    ["Gabon","GA"],
    ["Gambie","GM"],
    ["Georgia","GE"],
    ["Allemagne","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Grèce","GR"],
    ["Groenland","GL"],
    ["Grenade","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinée","GN"],
    ["Guinée-Bissau","GW"],
    ["Guyana","GY"],
    ["Haïti","HT"],
    ["Îles Heard et McDonald","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Hongrie","HU"],
    ["Iceland","IS"],
    ["India","IN"],
    ["Indonésie","ID"],
    ["Iran, République islamique d '","IR"],
    ["Irak","IQ"],
    ["Irlande","IE"],
    ["Isle of Man","IM"],
    ["Israël","IL"],
    ["Italie","IT"],
    ["Jamaica","JM"],
    ["Japon","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazakhstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["La Corée, République populaire démocratique de","KP"],
    ["La Corée, République de","KR"],
    ["Koweït","KW"],
    ["Kirghizistan","KG"],
    ["Lao République démocratique populaire","LA"],
    ["Lettonie","LV"],
    ["Liban","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libye","LY"],
    ["Liechtenstein","LI"],
    ["Lituanie","LT"],
    ["Luxembourg","LU"],
    ["Macao","MO"],
    ["Macédoine","MK"],
    ["Madagascar","MG"],
    ["Malawi","MW"],
    ["Malaisie","MY"],
    ["Maldives","MV"],
    ["Mali","ML"],
    ["Malte","MT"],
    ["Îles Marshall","MH"],
    ["Martinique","MQ"],
    ["Mauritanie","MR"],
    ["Maurice","MU"],
    ["Mayotte","YT"],
    ["Mexico","MX"],
    ["Micronésie, États fédérés de","FM"],
    ["Moldova, République de","MD"],
    ["Monaco","MC"],
    ["Mongolie","MN"],
    ["Monténégro","ME"],
    ["Montserrat","MS"],
    ["Maroc","MA"],
    ["Mozambique","MZ"],
    ["Myanmar","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Pays-Bas","NL"],
    ["Nouvelle-Calédonie","NC"],
    ["Nouvelle-Zélande","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Nioué","NU"],
    ["Norfolk Island","NF"],
    ["Îles Mariannes du Nord","MP"],
    ["Norvège","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestine","PS"],
    ["Panama","PA"],
    ["Papouasie-Nouvelle-Guinée","PG"],
    ["Paraguay","PY"],
    ["Pérou","PE"],
    ["Philippines","PH"],
    ["Pitcairn","PN"],
    ["Pologne","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Réunion","RE"],
    ["Roumanie","RO"],
    ["Fédération de Russie","RU"],
    ["Rwanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Sainte-Hélène et Tristan da Cunha","SH"],
    ["Saint-Kitts-et-Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (partie française)","MF"],
    ["Saint-Pierre-et-Miquelon","PM"],
    ["Saint-Vincent-et-les-Grenadines","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tomé-et-Principe","ST"],
    ["Arabie Saoudite","SA"],
    ["Sénégal","SN"],
    ["Serbie","RS"],
    ["Seychelles","SC"],
    ["Sierra Leone","SL"],
    ["Singapour","SG"],
    ["Sint Maarten (partie néerlandaise)","SX"],
    ["Slovaquie","SK"],
    ["Slovénie","SI"],
    ["Îles Salomon","SB"],
    ["Somalie","SO"],
    ["Afrique du Sud","ZA"],
    ["Géorgie du Sud","GS"],
    ["Sud-Soudan","SS"],
    ["Espagne","ES"],
    ["Sri Lanka","LK"],
    ["Soudan","SD"],
    ["Suriname","SR"],
    ["Svalbard et Jan Mayen","SJ"],
    ["Swaziland","SZ"],
    ["Suède","SE"],
    ["Suisse","CH"],
    ["République arabe syrienne","SY"],
    ["Taiwan, province de Chine","TW"],
    ["Tadjikistan","TJ"],
    ["Tanzanie, République-Unie de","TZ"],
    ["Thaïlande","TH"],
    ["Timor-Leste","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinité-et-Tobago","TT"],
    ["Tunisie","TN"],
    ["Turquie","TR"],
    ["Turkménistan","TM"],
    ["Îles Turques et Caïques","TC"],
    ["Tuvalu","TV"],
    ["Ouganda","UG"],
    ["Ukraine","UA"],
    ["Emirats Arabes Unis","AE"],
    ["Royaume-Uni","GB"],
    ["Etats-Unis","US"],
    ["États-Unis Îles mineures éloignées","UM"],
    ["Uruguay","UY"],
    ["Ouzbékistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatican","VA"],
    ["Venezuela, République bolivarienne du","VE"],
    ["Viet Nam","VN"],
    ["Îles Vierges britanniques","VG"],
    ["Îles Vierges, U.S.","VI"],
    ["Wallis et Futuna","WF"],
    ["Sahara Occidental","EH"],
    ["Yémen","YE"],
    ["La Zambie","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}