Q.Places.countries = [
    ["Afganistan","AF"],
    ["Álandseyjar","AX"],
    ["Albanía","AL"],
    ["Alsír","DZ"],
    ["American Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antígva og Barbúda","AG"],
    ["Argentina","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Austria","AT"],
    ["Aserbaídsjan","AZ"],
    ["Bahamas","BS"],
    ["Bahrain","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Hvíta","BY"],
    ["Belgía","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bútan","BT"],
    ["Bolivia, Plurinational Ríki","BO"],
    ["Bonaire, Saint Eustatius og Saba","BQ"],
    ["Bosnía og Hersegóvína","BA"],
    ["Botswana","BW"],
    ["Bouvet Island","BV"],
    ["Brasilía","BR"],
    ["British Indian Ocean Territory","IO"],
    ["Brunei Darussalam","BN"],
    ["Búlgaría","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambódía","KH"],
    ["Kamerún","CM"],
    ["Canada","CA"],
    ["Cape Verde","CV"],
    ["Caymaneyjar","KY"],
    ["Central African Republic","CF"],
    ["Chad","TD"],
    ["Chile","CL"],
    ["Kína","CN"],
    ["Jólaeyja","CX"],
    ["Cocos (Keeling) Islands","CC"],
    ["Colombia","CO"],
    ["Kómoreyjar","KM"],
    ["Kongó","CG"],
    ["Kongó, The Democratic Republic af","CD"],
    ["Cooks-eyjar","CK"],
    ["Costa Rica","CR"],
    ["Côte d'Ivoire","CI"],
    ["Croatia","HR"],
    ["Cuba","CU"],
    ["Curaçao","CW"],
    ["Kýpur","CY"],
    ["Tékkland","CZ"],
    ["Danmörk","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Dóminíska lýðveldið","DO"],
    ["Ecuador","EC"],
    ["Egyptaland","EG"],
    ["El Salvador","SV"],
    ["Miðbaugs-Gínea","GQ"],
    ["Eritrea","ER"],
    ["Eistland","EE"],
    ["Eþíópía","ET"],
    ["Falkland Islands (Malvinas)","FK"],
    ["Faroe Islands","FO"],
    ["Fiji","FJ"],
    ["Finnland","FI"],
    ["Frakkland","FR"],
    ["Franska Gvæjana","GF"],
    ["Franska Pólýnesía","PF"],
    ["Frönsku suðlægu landsvæðin","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Þýskaland","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Grikkland","GR"],
    ["Grænland","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haítí","HT"],
    ["Heard og McDonald-eyjar","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Hungary","HU"],
    ["Ísland","IS"],
    ["India","IN"],
    ["Indónesía","ID"],
    ["Íran, Íslamska lýðveldið","IR"],
    ["Írak","IQ"],
    ["Írland","IE"],
    ["Mön","IM"],
    ["Ísrael","IL"],
    ["Ítalía","IT"],
    ["Jamaica","JM"],
    ["Japan","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kasakstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Kórea Democratic fólks","KP"],
    ["Norður-Kórea","KR"],
    ["Kuwait","KW"],
    ["Kirgisistan","KG"],
    ["Lao Democratic Alþýðulýðveldisins","LA"],
    ["Latvia","LV"],
    ["Líbanon","LB"],
    ["Lesotho","LS"],
    ["Líbería","LR"],
    ["Libya","LY"],
    ["Liechtenstein","LI"],
    ["Litháen","LT"],
    ["Luxembourg","LU"],
    ["Macao","MO"],
    ["Makedónía","MK"],
    ["Madagascar","MG"],
    ["Malawi","MW"],
    ["Malasía","MY"],
    ["Maldíveyjar","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshall Islands","MH"],
    ["Martinique","MQ"],
    ["Mauritania","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mexico","MX"],
    ["Míkrónesía af","FM"],
    ["Moldavía, Lýðveldið","MD"],
    ["Monaco","MC"],
    ["Mongólía","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Marokkó","MA"],
    ["Mósambík","MZ"],
    ["Myanmar","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Holland","NL"],
    ["New Caledonia","NC"],
    ["New Zealand","NZ"],
    ["Níkaragva","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Northern Mariana Islands","MP"],
    ["Noregur","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestine","PS"],
    ["Panama","PA"],
    ["Papua New Guinea","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Philippines","PH"],
    ["Pitcairn","PN"],
    ["Pólland","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Katar","QA"],
    ["Réunion","RE"],
    ["Rúmenía","RO"],
    ["Russian Federation","RU"],
    ["Rúanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena og Tristan da Cunha","SH"],
    ["Sankti Kristófer og Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (French hluti)","MF"],
    ["Saint Pierre og Miquelon","PM"],
    ["Sankti Vinsent og Grenadíneyjar","VC"],
    ["Samóa","WS"],
    ["San Marino","SM"],
    ["Saó Tóme og Prinsípe","ST"],
    ["Saudi Arabia","SA"],
    ["Senegal","SN"],
    ["Serbía","RS"],
    ["Seychelles","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (hollensk hluti)","SX"],
    ["Slovakia","SK"],
    ["Slovenia","SI"],
    ["Salómonseyjar","SB"],
    ["Sómalía","SO"],
    ["South Africa","ZA"],
    ["South Georgia","GS"],
    ["South Sudan","SS"],
    ["Spánn","ES"],
    ["Sri Lanka","LK"],
    ["Súdan","SD"],
    ["Suriname","SR"],
    ["Svalbarði og Jan Mayen","SJ"],
    ["Svasíland","SZ"],
    ["Svíþjóð","SE"],
    ["Sviss","CH"],
    ["Sýrland","SY"],
    ["Taiwan, Province í Kína","TW"],
    ["Tadsjikistan","TJ"],
    ["Tansanía af","TZ"],
    ["Taíland","TH"],
    ["Timor-Leste","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trínidad og Tóbagó","TT"],
    ["Tunisia","TN"],
    ["Tyrkland","TR"],
    ["Túrkmenistan","TM"],
    ["Turks og Caicos Islands","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Úkraína","UA"],
    ["Sameinuðu arabísku furstadæmin","AE"],
    ["United Kingdom","GB"],
    ["United States","US"],
    ["United States Smáeyjar","UM"],
    ["Uruguay","UY"],
    ["Úsbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatican City State","VA"],
    ["Venezuela, Bolivarian Lýðveldið","VE"],
    ["Viet Nam","VN"],
    ["Virgin Islands, British","VG"],
    ["Virgin Islands, bandarískt.","VI"],
    ["Wallis og Futuna","WF"],
    ["Western Sahara","EH"],
    ["Jemen","YE"],
    ["Sambía","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}