Q.Places.countries = [
    ["Afganistanas","AF"],
    ["Alandų salos","AX"],
    ["Albanija","AL"],
    ["Alžyras","DZ"],
    ["Amerikos Samoa","AS"],
    ["Andora","AD"],
    ["Angoloje","AO"],
    ["Angilija","AI"],
    ["Antarktida","AQ"],
    ["Antigva ir Barbuda","AG"],
    ["Argentina","AR"],
    ["Armėnija","AM"],
    ["Aruba","AW"],
    ["Australija","AU"],
    ["Austrija","AT"],
    ["Azerbaidžanas","AZ"],
    ["Bahamai","BS"],
    ["Bahreinas","BH"],
    ["Bangladešas","BD"],
    ["Barbadosas","BB"],
    ["Baltarusija","BY"],
    ["Belgija","BE"],
    ["Belizas","BZ"],
    ["Beninas","BJ"],
    ["Bermudai","BM"],
    ["Butanas","BT"],
    ["Bolivija, Daugiatautė narė","BO"],
    ["Bonairė, Sint Eustatijus ir Saba","BQ"],
    ["Bosnija ir Hercegovina","BA"],
    ["Botsvana","BW"],
    ["Bouvet sala","BV"],
    ["Brazilija","BR"],
    ["Indijos vandenyno britų sritis","IO"],
    ["Brunėjus","BN"],
    ["Bulgarija","BG"],
    ["Burkina Fasas","BF"],
    ["Burundis","BI"],
    ["Kambodža","KH"],
    ["Kamerūnas","CM"],
    ["Kanada","CA"],
    ["Žaliasis Kyšulys","CV"],
    ["Cayman Islands","KY"],
    ["Centrinė Afrikos Respublika","CF"],
    ["Čadas","TD"],
    ["Čilė","CL"],
    ["Kinija","CN"],
    ["Kalėdų sala","CX"],
    ["Kokosų (Kylingo) salos","CC"],
    ["Kolumbija","CO"],
    ["Komorai","KM"],
    ["Kongas","CG"],
    ["Kongas, Demokratinė Respublika","CD"],
    ["Kuko salos","CK"],
    ["Kosta Rika","CR"],
    ["Dramblio Kaulo Krantas","CI"],
    ["Kroatija","HR"],
    ["Kuba","CU"],
    ["Kiurasao","CW"],
    ["Kipras","CY"],
    ["Čekija","CZ"],
    ["Danija","DK"],
    ["Džibutis","DJ"],
    ["Dominika","DM"],
    ["Dominikos Respublika","DO"],
    ["Ekvadoras","EC"],
    ["Egiptas","EG"],
    ["Salvadoras","SV"],
    ["Pusiaujo Gvinėja","GQ"],
    ["Eritrėja","ER"],
    ["Estija","EE"],
    ["Etiopija","ET"],
    ["Falklando salos (Malvinų)","FK"],
    ["Farerų salos","FO"],
    ["Fidžis","FJ"],
    ["Suomija","FI"],
    ["Prancūzija","FR"],
    ["Prancūzų Gviana","GF"],
    ["Prancūzų Polinezija","PF"],
    ["French Southern Territories","TF"],
    ["Gabonas","GA"],
    ["Gambija","GM"],
    ["Gruzija","GE"],
    ["Vokietija","DE"],
    ["Gana","GH"],
    ["Gibraltaras","GI"],
    ["Graikija","GR"],
    ["Grenlandija","GL"],
    ["Grenada","GD"],
    ["Gvadelupė","GP"],
    ["Guamas","GU"],
    ["Gvatemala","GT"],
    ["Gernsio","GG"],
    ["Gvinėja","GN"],
    ["Bisau Gvinėja","GW"],
    ["Gajana","GY"],
    ["Haitis","HT"],
    ["Heardo ir McDonaldo salos","HM"],
    ["Hondūras","HN"],
    ["Honkongas","HK"],
    ["Vengrija","HU"],
    ["Islandija","IS"],
    ["Indija","IN"],
    ["Indonezija","ID"],
    ["Irano Islamo Respublika","IR"],
    ["Irakas","IQ"],
    ["Airija","IE"],
    ["Isle of Man","IM"],
    ["Izraelis","IL"],
    ["Italija","IT"],
    ["Jamaika","JM"],
    ["Japonija","JP"],
    ["Jersey","JE"],
    ["Jordanijos","JO"],
    ["Kazachstanas","KZ"],
    ["Kenija","KE"],
    ["Kiribatis","KI"],
    ["Korėja, Demokratinė Liaudies Respublika","KP"],
    ["Korėjos Respublika","KR"],
    ["Kuveitas","KW"],
    ["Kirgizija","KG"],
    ["Laoso Liaudies Demokratinė Respublika","LA"],
    ["Latvija","LV"],
    ["Libanas","LB"],
    ["Lesotas","LS"],
    ["Liberija","LR"],
    ["Libija","LY"],
    ["Lichtenšteinas","LI"],
    ["Lietuva","LT"],
    ["Liuksemburgas","LU"],
    ["Makao","MO"],
    ["Makedonija","MK"],
    ["Madagaskaras","MG"],
    ["Malavis","MW"],
    ["Malaizijos ","MY"],
    ["Maldyvai","MV"],
    ["Malis","ML"],
    ["Malta","MT"],
    ["Maršalo salos","MH"],
    ["Martinika","MQ"],
    ["Mauritanija","MR"],
    ["Mauricijus","MU"],
    ["Majotas","YT"],
    ["Meksika","MX"],
    ["Mikronezijos Federacinės Valstijos","FM"],
    ["Moldovos Respublika","MD"],
    ["Monako","MC"],
    ["Mongolija","MN"],
    ["Juodkalnija","ME"],
    ["Montseratas","MS"],
    ["Marokas","MA"],
    ["Mozambikas","MZ"],
    ["Mianmaras","MM"],
    ["Namibija","NA"],
    ["Nauru","NR"],
    ["Nepalas","NP"],
    ["Olandija","NL"],
    ["Naujoji Kaledonija","NC"],
    ["Naujoji Zelandija","NZ"],
    ["Nikaragva","NI"],
    ["Nigeris","NE"],
    ["Nigerija","NG"],
    ["Niujė","NU"],
    ["Norfolko sala","NF"],
    ["Marianos Šiaurinės Salos","MP"],
    ["Norvegija","NO"],
    ["Omanas","OM"],
    ["Pakistanas","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panamos","PA"],
    ["Papua Naujoji Gvinėja","PG"],
    ["Paragvajus","PY"],
    ["Peru","PE"],
    ["Filipinai","PH"],
    ["Pitkernas","PN"],
    ["Lenkija","PL"],
    ["Portugalija","PT"],
    ["Puerto Riko","PR"],
    ["Kataras","QA"],
    ["Reunionas","RE"],
    ["Rumunija","RO"],
    ["Rusija","RU"],
    ["Ruanda","RW"],
    ["Švento Baltramiejaus sala","BL"],
    ["Elenos sala ir Tristanas da Cunha","SH"],
    ["Sent Kitsas ir Nevis","KN"],
    ["Sent Lusija","LC"],
    ["Saint Martin (Prancūzijos dalis)","MF"],
    ["Sent Pjeras ir Mikelonas","PM"],
    ["Saint Vincentas ir Grenadinai","VC"],
    ["Samoa","WS"],
    ["San Marinas","SM"],
    ["San Tomė ir Prinsipė","ST"],
    ["Saudo Arabija","SA"],
    ["Senegalas","SN"],
    ["Serbija","RS"],
    ["Seišeliai","SC"],
    ["Siera Leonė","SL"],
    ["Singapūras","SG"],
    ["Sint Martenas (Nyderlandų dalis)","SX"],
    ["Slovakija","SK"],
    ["Slovėnija","SI"],
    ["Saliamono Salos","SB"],
    ["Somalis","SO"],
    ["Pietų Afrika","ZA"],
    ["Pietų Džordžija","GS"],
    ["Pietų Sudanas","SS"],
    ["Ispanija","ES"],
    ["Šri Lanka","LK"],
    ["Sudanas","SD"],
    ["Surinamas","SR"],
    ["Svalbardas ir Jan Mayenas","SJ"],
    ["Svazilendas","SZ"],
    ["Švedija","SE"],
    ["Šveicarija","CH"],
    ["Sirijos Arabų Respublika","SY"],
    ["Taivanas, Kinijos provincija","TW"],
    ["Tadžikistanas","TJ"],
    ["Tanzanijos Jungtinė Respublika","TZ"],
    ["Tailandas","TH"],
    ["Rytų Timorą","TL"],
    ["Togas","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidadas ir Tobagas","TT"],
    ["Tunisas","TN"],
    ["Turkija","TR"],
    ["Turkmėnistanas","TM"],
    ["Turkso ir Caicoso salos","TC"],
    ["Tuvalu","TV"],
    ["Ugandoje","UG"],
    ["Ukraina","UA"],
    ["Jungtiniai Arabų Emyratai","AE"],
    ["Jungtinė Karalystė","GB"],
    ["Jungtinės Valstijos","US"],
    ["Jungtinių Valstijų mažosios aplinkinės salos","UM"],
    ["Urugvajus","UY"],
    ["Uzbekistanas","UZ"],
    ["Vanuatu","VU"],
    ["Vatikanas","VA"],
    ["Venesuelos Bolivaro Respublika","VE"],
    ["Vietnamas","VN"],
    ["Virgin Islands, British","VG"],
    ["Virgin Islands, Ne JAV.","VI"],
    ["Volis ir Futūna","WF"],
    ["Vakarinė Sachara","EH"],
    ["Jemenas","YE"],
    ["Zambija","ZM"],
    ["Zimbabvė","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}