Q.Places.countries = [
    ["Afganistāna","AF"],
    ["Ālandu salas","AX"],
    ["Albānija","AL"],
    ["Alžīrija","DZ"],
    ["American Samoa","AS"],
    ["Andora","AD"],
    ["Angola","AO"],
    ["Angilja","AI"],
    ["Antarktīda","AQ"],
    ["Antigva un Barbuda","AG"],
    ["Argentīna","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Austrija","AT"],
    ["Azerbaidžāna","AZ"],
    ["Bahamas","BS"],
    ["Bahreïn","BH"],
    ["Bangladeša","BD"],
    ["Barbadosa","BB"],
    ["Belarus","BY"],
    ["Belgium","BE"],
    ["Beliza","BZ"],
    ["Benina","BJ"],
    ["Bermuda","BM"],
    ["Butāna","BT"],
    ["Bolīvijas Daudznacionālā valsts","BO"],
    ["Bonaire, Sintestatiusa un Saba","BQ"],
    ["Bosnija un Hercegovina","BA"],
    ["Botsvāna","BW"],
    ["Buvē sala","BV"],
    ["Brazīlija","BR"],
    ["Britu Indijas okeāna teritorija","IO"],
    ["Bruneja","BN"],
    ["Bulgārija","BG"],
    ["Burkinafaso","BF"],
    ["Burundi","BI"],
    ["Kambodža","KH"],
    ["Kamerūna","CM"],
    ["Kanāda","CA"],
    ["Cape Verde","CV"],
    ["Kaimanu salas","KY"],
    ["Centrālāfrikas Republika","CF"],
    ["Čada","TD"],
    ["Čīle","CL"],
    ["Ķīna","CN"],
    ["Ziemassvētku sala","CX"],
    ["Kokosu (Kīlinga) salas","CC"],
    ["Kolumbija","CO"],
    ["Komoru salas","KM"],
    ["Congo","CG"],
    ["Kongo Demokrātiskā Republika","CD"],
    ["Kuka salas","CK"],
    ["Kostarika","CR"],
    ["Kotdivuāra","CI"],
    ["Horvātija","HR"],
    ["Cuba","CU"],
    ["Kirasao","CW"],
    ["Kipra","CY"],
    ["Čehijas Republika","CZ"],
    ["Dānija","DK"],
    ["Džibutija","DJ"],
    ["Dominika","DM"],
    ["Dominikānas Republika","DO"],
    ["Ekvadora","EC"],
    ["Ēģipte","EG"],
    ["El Salvador","SV"],
    ["Ekvatoriālā Gvineja","GQ"],
    ["Eritreja","ER"],
    ["Estonia","EE"],
    ["Etiopija","ET"],
    ["Folklenda salas (Malvinu)","FK"],
    ["Farēru salas","FO"],
    ["Fidži","FJ"],
    ["Somija","FI"],
    ["Francija","FR"],
    ["Franču Gviāna","GF"],
    ["Franču Polinēzija","PF"],
    ["Francijas Dienvidjūru teritorija","TF"],
    ["Gabona","GA"],
    ["Gambija","GM"],
    ["Georgia","GE"],
    ["Vācija","DE"],
    ["Gana","GH"],
    ["Gibraltārs","GI"],
    ["Grieķija","GR"],
    ["Grenlande","GL"],
    ["Grenāda","GD"],
    ["Gvadelupa","GP"],
    ["Guama","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Gvineja","GN"],
    ["Gvineja-Bisava","GW"],
    ["Gajāna","GY"],
    ["Haiti","HT"],
    ["Heard Island un McDonald Islands","HM"],
    ["Hondurasa","HN"],
    ["Hong Kong","HK"],
    ["Ungārija","HU"],
    ["Islande","IS"],
    ["India","IN"],
    ["Indonēzija","ID"],
    ["Irānas Islāma Republika","IR"],
    ["Irāka","IQ"],
    ["Īrija","IE"],
    ["Isle of Man","IM"],
    ["Izraēla","IL"],
    ["Itālija","IT"],
    ["Jamaika","JM"],
    ["Japāna","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazahstāna","KZ"],
    ["Kenija","KE"],
    ["Kiribati","KI"],
    ["Korejas Tautas Demokrātiskā Republika","KP"],
    ["Korea, Republic of","KR"],
    ["Kuveita","KW"],
    ["Kirgizstāna","KG"],
    ["Laosas Tautas Demokrātiskā Republika","LA"],
    ["Latvija","LV"],
    ["Libāna","LB"],
    ["Lesoto","LS"],
    ["Libērija","LR"],
    ["Lībija","LY"],
    ["Lihtenšteina","LI"],
    ["Lietuva","LT"],
    ["Luxembourg","LU"],
    ["Makao","MO"],
    ["Maķedonija","MK"],
    ["Madagaskara","MG"],
    ["Malāvija","MW"],
    ["Malaizija","MY"],
    ["Maldivu","MV"],
    ["Mali","ML"],
    ["Maltas","MT"],
    ["Māršala salas","MH"],
    ["Martinika","MQ"],
    ["Mauritānija","MR"],
    ["Maurīcija","MU"],
    ["Majota","YT"],
    ["Meksika","MX"],
    ["Mikronēzijas Federatīvās Valstis","FM"],
    ["Moldova, Republic of","MD"],
    ["Monaco","MC"],
    ["Mongolija","MN"],
    ["Melnkalne","ME"],
    ["Montserrat","MS"],
    ["Maroka","MA"],
    ["Mozambika","MZ"],
    ["Mjanma","MM"],
    ["Namībija","NA"],
    ["Nauru","NR"],
    ["Nepāla","NP"],
    ["Nīderlande","NL"],
    ["Jaunkaledonija","NC"],
    ["New Zealand","NZ"],
    ["Nikaragva","NI"],
    ["Nigēra","NE"],
    ["Nigērija","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Ziemeļu Marianas salas","MP"],
    ["Norvēģija","NO"],
    ["Omāna","OM"],
    ["Pakistāna","PK"],
    ["Palau","PW"],
    ["Palestīna","PS"],
    ["Panama","PA"],
    ["Papua Jaungvineja","PG"],
    ["Paragvaja","PY"],
    ["Peru","PE"],
    ["Filipīnas","PH"],
    ["Pitkērna","PN"],
    ["Polija","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Katara","QA"],
    ["Reinjona","RE"],
    ["Rumānija","RO"],
    ["Krievija","RU"],
    ["Ruanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena un Tristana da Cunha","SH"],
    ["Sentkitsa un Nevisa","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (Francijas daļa)","MF"],
    ["Senpjēra un Mikelona","PM"],
    ["Sentvinsenta un Grenadīnas","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Santome un Prinsipi","ST"],
    ["Saūda Arābija","SA"],
    ["Senegāla","SN"],
    ["Serbija","RS"],
    ["Seišelu salas","SC"],
    ["Sierra Leone","SL"],
    ["Singapūra","SG"],
    ["Sint Maarten (Nīderlandes daļa)","SX"],
    ["Slovakia","SK"],
    ["Slovēnija","SI"],
    ["Zālamana salas","SB"],
    ["Somālija","SO"],
    ["South Africa","ZA"],
    ["South Georgia","GS"],
    ["Dienvidsudāna","SS"],
    ["Spānija","ES"],
    ["Sri Lanka","LK"],
    ["Sudāna","SD"],
    ["Surinama","SR"],
    ["Svalbāra un Jana Majena sala","SJ"],
    ["Svazilenda","SZ"],
    ["Zviedrija","SE"],
    ["Šveice","CH"],
    ["Sīrijas Arābu Republika","SY"],
    ["Taiwan, Province of China","TW"],
    ["Tadžikistāna","TJ"],
    ["Tanzānija, Tanzānijas Apvienotā Republika","TZ"],
    ["Taizeme","TH"],
    ["Austrumtimora","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidāda un Tobago","TT"],
    ["Tunisija","TN"],
    ["Turcija","TR"],
    ["Turkmenistāna","TM"],
    ["Tērksas un Kaikosas salas","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraina","UA"],
    ["Apvienotie Arābu Emirāti","AE"],
    ["United Kingdom","GB"],
    ["United States","US"],
    ["ASV Mazās Aizjūras salas","UM"],
    ["Urugvaja","UY"],
    ["Uzbekistāna","UZ"],
    ["Vanuatu","VU"],
    ["Vatikāns","VA"],
    ["Venecuēla, Bolivāra Republika","VE"],
    ["Viet Nam","VN"],
    ["Virdžīnu salas, Britu","VG"],
    ["Virdžīnu salas, kas neatrodas ASV.","VI"],
    ["Volisa un Futuna","WF"],
    ["Western Sahara","EH"],
    ["Jemena","YE"],
    ["Zambija","ZM"],
    ["Zimbabve","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}