Q.Places.countries = [
    ["L-Afganistan","AF"],
    ["Åland Gżejjer","AX"],
    ["L-Albanija","AL"],
    ["L-Alġerija","DZ"],
    ["Samoa Amerikana","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antartika","AQ"],
    ["Antigwa u Barbuda","AG"],
    ["L-Arġentina","AR"],
    ["Armenja","AM"],
    ["Aruba","AW"],
    ["Awstralja","AU"],
    ["Awstrija","AT"],
    ["Ażerbajġan","AZ"],
    ["Baħamas","BS"],
    ["Bahrain","BH"],
    ["Bangladexx","BD"],
    ["Barbados","BB"],
    ["Il-Belarus","BY"],
    ["Belġju","BE"],
    ["Beliże","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Butan","BT"],
    ["Bolivja, Stat Plurinazzjonali ta '","BO"],
    ["Bonaire, Sint Eustatius u Saba","BQ"],
    ["Bosnija u Ħerżegovina","BA"],
    ["Botswana","BW"],
    ["Bouvet Island","BV"],
    ["Il-Brażil","BR"],
    ["Territorju Britanniku fl-Oċean Indjan","IO"],
    ["Brunej Darussalam","BN"],
    ["Bulgarija","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambodja","KH"],
    ["Kamerun","CM"],
    ["Kanada","CA"],
    ["Kap Verde","CV"],
    ["Gżejjer Cayman","KY"],
    ["Repubblika Ċentrali Afrikana","CF"],
    ["Ċad","TD"],
    ["Ċili","CL"],
    ["Ċina","CN"],
    ["Christmas Island","CX"],
    ["Cocos (Keeling) Gżejjer","CC"],
    ["Kolombja","CO"],
    ["Komoros","KM"],
    ["Kongo","CG"],
    ["Kongo, ir-Repubblika Demokratika tal-","CD"],
    ["Gżejjer Cook","CK"],
    ["Kosta Rika","CR"],
    ["Côte d'Ivoire","CI"],
    ["Il-Kroazja","HR"],
    ["Kuba","CU"],
    ["Curaçao","CW"],
    ["Ċipru","CY"],
    ["Repubblika Ċeka","CZ"],
    ["Danimarka","DK"],
    ["Ġibuti","DJ"],
    ["Dominika","DM"],
    ["Ir-Repubblika Dominikana","DO"],
    ["Ekwador","EC"],
    ["Eġittu","EG"],
    ["El Salvador","SV"],
    ["Ginea Ekwatorjali","GQ"],
    ["L-Eritrea","ER"],
    ["L-Estonja","EE"],
    ["Etjopja","ET"],
    ["Falkland Gżejjer (Malvinas)","FK"],
    ["Gżejjer Faroe","FO"],
    ["Fiġi","FJ"],
    ["Il-Finlandja","FI"],
    ["Franza","FR"],
    ["Gujana Franċiża","GF"],
    ["Polineżja Franċiża","PF"],
    ["Territorji Franċiżi tan-Nofsinhar","TF"],
    ["Gabon","GA"],
    ["Gambja","GM"],
    ["Ġorġja","GE"],
    ["Il-Ġermanja","DE"],
    ["Gana","GH"],
    ["Ġibiltà","GI"],
    ["Greċja","GR"],
    ["Greenland","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Gwam","GU"],
    ["Gwatemala","GT"],
    ["Guernsey","GG"],
    ["Ginea","GN"],
    ["Ginea-Bissaw","GW"],
    ["Gujana","GY"],
    ["Ħaiti","HT"],
    ["Il-Gżira Heard u McDonald Gżejjer","HM"],
    ["Ħonduras","HN"],
    ["Ħong Kong","HK"],
    ["L-Ungerija","HU"],
    ["L-Iżlanda","IS"],
    ["L-Indja","IN"],
    ["L-Indoneżja","ID"],
    ["L-Iran, Repubblika Islamika ta '","IR"],
    ["L-Iraq","IQ"],
    ["Irlanda","IE"],
    ["Isle of Man","IM"],
    ["L-Iżrael","IL"],
    ["L-Italja","IT"],
    ["Ġamajka","JM"],
    ["Ġappun","JP"],
    ["Jersey","JE"],
    ["Il-Ġordan","JO"],
    ["Każakstan","KZ"],
    ["Kenja","KE"],
    ["Kiribati","KI"],
    ["Il-Korea, ir-Repubblika Demokratika Popolari tal-","KP"],
    ["Il-Korea, Repubblika ta '","KR"],
    ["Kuwajt","KW"],
    ["Kirgistan","KG"],
    ["Laos Repubblika Demokratika Poplu","LA"],
    ["Il-Latvja","LV"],
    ["Il-Libanu","LB"],
    ["Lesoto","LS"],
    ["-Liberja","LR"],
    ["Libja","LY"],
    ["Il-Liechtenstein","LI"],
    ["Litwanja","LT"],
    ["Lussemburgu","LU"],
    ["Makaw","MO"],
    ["Maċedonja","MK"],
    ["Madagaskar","MG"],
    ["Malawi","MW"],
    ["Malasja","MY"],
    ["Maldivi","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Gżejjer Marshall","MH"],
    ["Martinique","MQ"],
    ["Il-Mawritanja","MR"],
    ["Il-Mawrizju","MU"],
    ["Mayotte","YT"],
    ["Il-Messiku","MX"],
    ["Mikronesja, Stati Federati tal-","FM"],
    ["Il-Moldova, Repubblika ta '","MD"],
    ["Monako","MC"],
    ["Mongolja","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Il-Marokk","MA"],
    ["Il-Możambik","MZ"],
    ["Mjanmar","MM"],
    ["Namibja","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Olanda","NL"],
    ["Kaledonja Ġdida","NC"],
    ["New Zealand","NZ"],
    ["Nikaragwa","NI"],
    ["Niġer","NE"],
    ["Niġerja","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Tramuntana Gżejjer Mariana","MP"],
    ["In-Norveġja","NO"],
    ["Oman","OM"],
    ["Il-Pakistan","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panama","PA"],
    ["Papwa Ginea Ġdida","PG"],
    ["Paragwaj","PY"],
    ["Peru","PE"],
    ["Filippini","PH"],
    ["Pitcairn","PN"],
    ["Polonja","PL"],
    ["Il-Portugall","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Réunion","RE"],
    ["Ir-Rumanija","RO"],
    ["Federazzjoni Russa","RU"],
    ["Rwanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena u Tristan da Cunha","SH"],
    ["Saint Kitts u Nevis","KN"],
    ["Santa Luċija","LC"],
    ["San Martin (parti Franċiża)","MF"],
    ["Saint Pierre u Miquelon","PM"],
    ["San Vinċenz u l-Grenadini","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome u Prinċipe","ST"],
    ["Għarabja Sawdita","SA"],
    ["Senegal","SN"],
    ["Serbja","RS"],
    ["Seychelles","SC"],
    ["Sierra Leone","SL"],
    ["Singapor","SG"],
    ["Sint Maarten (parti Olandiża)","SX"],
    ["Is-Slovakkja","SK"],
    ["Slovenja","SI"],
    ["Gżejjer Solomon","SB"],
    ["Somalja","SO"],
    ["L-Afrika t'Isfel","ZA"],
    ["Ġeorġja tan-Nofsinhar","GS"],
    ["Sudan tan-Nofsinhar","SS"],
    ["Spanja","ES"],
    ["Is-Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Surinam","SR"],
    ["Svalbard u Jan Mayen","SJ"],
    ["Sważiland","SZ"],
    ["L-Isvezja","SE"],
    ["L-Isvizzera","CH"],
    ["Repubblika Għarbija Sirjana","SY"],
    ["Tajwan, Provinċja taċ-Ċina","TW"],
    ["Taġikistan","TJ"],
    ["Tanzanija, Repubblika Unita ta '","TZ"],
    ["Tajlandja","TH"],
    ["Timor-Leste","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad u Tobago","TT"],
    ["Tuneżija","TN"],
    ["It-Turkija","TR"],
    ["It-Turkmenistan","TM"],
    ["Turks u Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraina","UA"],
    ["Emirati Għarab Magħquda","AE"],
    ["Ir-Renju Unit","GB"],
    ["Stati Uniti","US"],
    ["Stati Uniti Gżejjer Minuri periferija","UM"],
    ["Urugwaj","UY"],
    ["Użbekistan","UZ"],
    ["Vanwatu","VU"],
    ["Istat tal-Vatikan","VA"],
    ["Venezwela, ir-Repubblika Bolivarjana tal-","VE"],
    ["Vjet Nam","VN"],
    ["Virgin Islands, British","VG"],
    ["Virgin Islands, U.S.","VI"],
    ["Wallis u Futuna","WF"],
    ["Saħara tal-Punent","EH"],
    ["Jemen","YE"],
    ["Żambja","ZM"],
    ["Żimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}