Q.Places.countries = [
    ["Afghanistan","AF"],
    ["Åland","AX"],
    ["Albanië","AL"],
    ["Algeria","DZ"],
    ["American Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antigua en Barbuda","AG"],
    ["Argentinië","AR"],
    ["Armenië","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Oostenrijk","AT"],
    ["Azerbeidzjan","AZ"],
    ["Bahamas","BS"],
    ["Bahrein","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Belarus","BY"],
    ["België","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Bolivia, Plurinationale Staat","BO"],
    ["Bonaire, Sint Eustatius en Saba","BQ"],
    ["Bosnië en Herzegovina","BA"],
    ["Botswana","BW"],
    ["Bouvet Island","BV"],
    ["Brazil","BR"],
    ["British Indian Ocean Territory","IO"],
    ["Brunei Darussalam","BN"],
    ["Bulgarije","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Cambodia","KH"],
    ["Kameroen","CM"],
    ["Canada","CA"],
    ["Cape Verde","CV"],
    ["Cayman Islands","KY"],
    ["Centraal-Afrikaanse Republiek","CF"],
    ["Chad","TD"],
    ["Chili","CL"],
    ["China","CN"],
    ["Christmas Island","CX"],
    ["Cocos (Keeling) Islands","CC"],
    ["Colombia","CO"],
    ["De Comoren","KM"],
    ["Congo","CG"],
    ["Congo, de Democratische Republiek","CD"],
    ["Cook Islands","CK"],
    ["Costa Rica","CR"],
    ["Côte d'Ivoire","CI"],
    ["Kroatië","HR"],
    ["Cuba","CU"],
    ["Curaçao","CW"],
    ["Cyprus","CY"],
    ["Tsjechië","CZ"],
    ["Denemarken","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Dominicaanse Republiek","DO"],
    ["Ecuador","EC"],
    ["Egypte","EG"],
    ["El Salvador","SV"],
    ["Equatoriaal-Guinea","GQ"],
    ["Eritrea","ER"],
    ["Estland","EE"],
    ["Ethiopië","ET"],
    ["Falkland Eilanden (Malvinas)","FK"],
    ["Faeröer","FO"],
    ["Fiji","FJ"],
    ["Finland","FI"],
    ["Frankrijk","FR"],
    ["Frans-Guyana","GF"],
    ["Frans-Polynesië","PF"],
    ["French Southern Territories","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Duitsland","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Griekenland","GR"],
    ["Greenland","GL"],
    ["Granada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinee-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Heard en McDonald-eilanden","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Hongarije","HU"],
    ["IJsland","IS"],
    ["India","IN"],
    ["Indonesië","ID"],
    ["Iran, Islamitische Republiek","IR"],
    ["Irak","IQ"],
    ["Ierland","IE"],
    ["Isle of Man","IM"],
    ["Israël","IL"],
    ["Italië","IT"],
    ["Jamaica","JM"],
    ["Japan","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazakhstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Korea, Democratische Volksrepubliek","KP"],
    ["Zuid Korea","KR"],
    ["Koeweit","KW"],
    ["Kyrgyzstan","KG"],
    ["Lao Democratische Volksrepubliek","LA"],
    ["Letland","LV"],
    ["Lebanon","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libië","LY"],
    ["Liechtenstein","LI"],
    ["Litouwen","LT"],
    ["Luxembourg","LU"],
    ["Macao","MO"],
    ["Macedonië","MK"],
    ["Madagascar","MG"],
    ["Malawi","MW"],
    ["Maleisië","MY"],
    ["Maldiven","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshall Eilanden","MH"],
    ["Martinique","MQ"],
    ["Mauritanië","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mexico","MX"],
    ["Micronesië, Federale Staten van","FM"],
    ["Moldova, Republic of","MD"],
    ["Monaco","MC"],
    ["Mongolië","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Marokko","MA"],
    ["Mozambique","MZ"],
    ["Birma","MM"],
    ["Namibië","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Nederland","NL"],
    ["Nieuw-Caledonië","NC"],
    ["Nieuw-Zeeland","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Noordelijke Marianen","MP"],
    ["Noorwegen","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panama","PA"],
    ["Papoea-Nieuw-Guinea","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Philippines","PH"],
    ["Pitcairneilanden","PN"],
    ["Polen","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Réunion","RE"],
    ["Roemenië","RO"],
    ["Russische Federatie","RU"],
    ["Rwanda","RW"],
    ["Saint-Barthélemy","BL"],
    ["Sint-Helena en Tristan da Cunha","SH"],
    ["Saint Kitts en Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (Franse gedeelte)","MF"],
    ["Saint-Pierre en Miquelon","PM"],
    ["Saint Vincent en de Grenadines","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tomé en Principe","ST"],
    ["Saoedi-Arabië","SA"],
    ["Senegal","SN"],
    ["Servië","RS"],
    ["De Seychellen","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (Nederlandse deel)","SX"],
    ["Slovakije","SK"],
    ["Slovenië","SI"],
    ["Solomon Islands","SB"],
    ["Somalië","SO"],
    ["Zuid-Afrika","ZA"],
    ["Zuid-Georgië","GS"],
    ["Zuid-Soedan","SS"],
    ["Spain","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Suriname","SR"],
    ["Svalbard en Jan Mayen","SJ"],
    ["Swaziland","SZ"],
    ["Zweden","SE"],
    ["Zwitserland","CH"],
    ["Syrische Arabische Republiek","SY"],
    ["Taiwan, provincie van China","TW"],
    ["Tajikistan","TJ"],
    ["Tanzania, Verenigde Republiek","TZ"],
    ["Thailand","TH"],
    ["Oost-Timor","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad en Tobago","TT"],
    ["Tunesië","TN"],
    ["Turkije","TR"],
    ["Turkmenistan","TM"],
    ["Turks- en Caicoseilanden","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Oekraïne","UA"],
    ["Verenigde Arabische Emiraten","AE"],
    ["Het Verenigd Koninkrijk","GB"],
    ["Verenigde Staten","US"],
    ["Kleine afgelegen eilanden van de Verenigde Staten","UM"],
    ["Uruguay","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vaticaanstad","VA"],
    ["Venezuela, Bolivariaanse Republiek","VE"],
    ["Vietnam","VN"],
    ["Britse Maagdeneilanden","VG"],
    ["Virgin Islands, het Amerikaanse.","VI"],
    ["Wallis en Futuna","WF"],
    ["Westelijke Sahara","EH"],
    ["Jemen","YE"],
    ["Zambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}