Q.Places.countries = [
    ["Afganistan","AF"],
    ["Wyspy Alandzkie","AX"],
    ["Albania","AL"],
    ["Algieria","DZ"],
    ["Samoa Amerykańskie","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antigua i Barbuda","AG"],
    ["Argentyna","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Austria","AT"],
    ["Azerbejdżan","AZ"],
    ["Bahamas","BS"],
    ["Bahrajn","BH"],
    ["Bangladesz","BD"],
    ["Barbados","BB"],
    ["Białoruś","BY"],
    ["Belgia","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Boliwia, Wielonarodowe Państwo","BO"],
    ["Bonaire, Sint Eustatius i Saba","BQ"],
    ["Bośnia i Hercegowina","BA"],
    ["Botswana","BW"],
    ["Bouvet Wyspa","BV"],
    ["Brazil","BR"],
    ["Brytyjskie Terytorium Oceanu Indyjskiego","IO"],
    ["Brunei Darussalam","BN"],
    ["Bułgaria","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Cambodia","KH"],
    ["Kamerun","CM"],
    ["Kanada","CA"],
    ["Cape Verde","CV"],
    ["Kajmany","KY"],
    ["Central African Republic","CF"],
    ["Czad","TD"],
    ["Chile","CL"],
    ["Chiny","CN"],
    ["Christmas Island","CX"],
    ["Cocos (Keeling) Islands","CC"],
    ["Kolumbia","CO"],
    ["Komory","KM"],
    ["Kongo","CG"],
    ["Kongo, Republika Demokratyczna","CD"],
    ["Wyspy Cooka","CK"],
    ["Kostaryka","CR"],
    ["Wybrzeże Kości Słoniowej","CI"],
    ["Chorwacja","HR"],
    ["Kuba","CU"],
    ["Curaçao","CW"],
    ["Cypr","CY"],
    ["Czechy","CZ"],
    ["Dania","DK"],
    ["Dżibuti","DJ"],
    ["Dominika","DM"],
    ["Dominikana","DO"],
    ["Ekwador","EC"],
    ["Egipt","EG"],
    ["Salwador","SV"],
    ["Gwinea Równikowa","GQ"],
    ["Erytrea","ER"],
    ["Estonia","EE"],
    ["Etiopia","ET"],
    ["Falklandy (Malwiny)","FK"],
    ["Wyspy Owcze","FO"],
    ["Fidżi","FJ"],
    ["Finlandia","FI"],
    ["Francja","FR"],
    ["Gujana Francuska","GF"],
    ["Polinezja Francuska","PF"],
    ["Francuskie Terytoria Południowe","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Gruzja","GE"],
    ["Niemcy","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Grecja","GR"],
    ["Greenland","GL"],
    ["Grenada","GD"],
    ["Gwadelupa","GP"],
    ["Guam","GU"],
    ["Gwatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Gwinea Bissau","GW"],
    ["Gujana","GY"],
    ["Haiti","HT"],
    ["Wyspy Heard i McDonalda Wyspy","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Węgry","HU"],
    ["Islandia","IS"],
    ["Indie","IN"],
    ["Indonezja","ID"],
    ["Iran, Islamska Republika","IR"],
    ["Irak","IQ"],
    ["Irlandia","IE"],
    ["Isle of Man","IM"],
    ["Izrael","IL"],
    ["Włochy","IT"],
    ["Jamajka","JM"],
    ["Japan","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazachstan","KZ"],
    ["Kenia","KE"],
    ["Kiribati","KI"],
    ["Koreańska Republika Ludowo-Demokratyczna","KP"],
    ["Republika Korei","KR"],
    ["Kuwejt","KW"],
    ["Kirgistan","KG"],
    ["Ludowo-Demokratyczna Republika","LA"],
    ["Łotwa","LV"],
    ["Liban","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libia","LY"],
    ["Liechtenstein","LI"],
    ["Litwa","LT"],
    ["Luksemburg","LU"],
    ["Macao","MO"],
    ["Macedonia","MK"],
    ["Madagaskar","MG"],
    ["Malawi","MW"],
    ["Malezja","MY"],
    ["Malediwy","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Wyspy Marshalla","MH"],
    ["Martynika","MQ"],
    ["Mauretania","MR"],
    ["Mauritius","MU"],
    ["Majotta","YT"],
    ["Meksyk","MX"],
    ["Mikronezja of","FM"],
    ["Mołdowa","MD"],
    ["Monako","MC"],
    ["Mongolia","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Maroko","MA"],
    ["Mozambik","MZ"],
    ["Birma","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Holandia","NL"],
    ["New Caledonia","NC"],
    ["Nowa Zelandia","NZ"],
    ["Nikaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Norfolk","NF"],
    ["Mariany Północne","MP"],
    ["Norwegia","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestyna","PS"],
    ["Panama","PA"],
    ["Papua Nowa Gwinea","PG"],
    ["Paragwaj","PY"],
    ["Peru","PE"],
    ["Filipiny","PH"],
    ["Pitcairn","PN"],
    ["Polska","PL"],
    ["Portugalia","PT"],
    ["Puerto Rico","PR"],
    ["Katar","QA"],
    ["Reunion","RE"],
    ["Rumunia","RO"],
    ["Federacja Rosyjska","RU"],
    ["Rwanda","RW"],
    ["Saint-Barthélemy","BL"],
    ["Święta Helena i Tristan da Cunha","SH"],
    ["Saint Kitts i Nevis","KN"],
    ["Santa Lucia","LC"],
    ["Saint Martin (część francuska)","MF"],
    ["Saint-Pierre i Miquelon","PM"],
    ["Saint Vincent i Grenadyny","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome i Principe","ST"],
    ["Arabia Saudyjska","SA"],
    ["Senegal","SN"],
    ["Serbia","RS"],
    ["Seszele","SC"],
    ["Sierra Leone","SL"],
    ["Singapur","SG"],
    ["Sint Maarten (część holenderska)","SX"],
    ["Slovakia","SK"],
    ["Słowenia","SI"],
    ["Wyspy Salomona","SB"],
    ["Somalia","SO"],
    ["Republika Południowej Afryki","ZA"],
    ["Georgia Południowa","GS"],
    ["Południowy Sudan","SS"],
    ["Hiszpania","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Surinam","SR"],
    ["Svalbard i Jan Mayen","SJ"],
    ["Suazi","SZ"],
    ["Szwecja","SE"],
    ["Szwajcaria","CH"],
    ["Syria","SY"],
    ["Taiwan, Province of China","TW"],
    ["Tadżykistan","TJ"],
    ["Tanzania, Zjednoczona Republika","TZ"],
    ["Tajlandia","TH"],
    ["Timor Wschodni","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trynidad i Tobago","TT"],
    ["Tunezja","TN"],
    ["Turcja","TR"],
    ["Turkmenistan","TM"],
    ["Turks i Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraina","UA"],
    ["Zjednoczone Emiraty Arabskie","AE"],
    ["Wielka Brytania","GB"],
    ["Stany Zjednoczone","US"],
    ["Stany Zjednoczone Dalekie Wyspy Mniejsze","UM"],
    ["Urugwaj","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Watykan","VA"],
    ["Wenezuela, Boliwariańskiej Republiki","VE"],
    ["Wietnam","VN"],
    ["Brytyjskie Wyspy Dziewicze","VG"],
    ["Wyspy Dziewicze, oprócz Stanów Zjednoczonych.","VI"],
    ["Wallis i Futuna","WF"],
    ["Sahara Zachodnia","EH"],
    ["Jemen","YE"],
    ["Zambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}