Q.Places.countries = [
    ["Afeganistão","AF"],
    ["Ilhas Åland","AX"],
    ["Albânia","AL"],
    ["Argélia","DZ"],
    ["Samoa Americana","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antígua e Barbuda","AG"],
    ["Argentina","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Áustria","AT"],
    ["Azerbaijão","AZ"],
    ["Bahamas","BS"],
    ["Bahrain","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Belarus","BY"],
    ["Bélgica","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Butão","BT"],
    ["A Bolívia, Estado Plurinacional da","BO"],
    ["Bonaire, Santo Eustáquio e Saba","BQ"],
    ["Bósnia e Herzegovina","BA"],
    ["Botswana","BW"],
    ["Bouvet Island","BV"],
    ["Brasil","BR"],
    ["British Indian Ocean Territory","IO"],
    ["Brunei Darussalam","BN"],
    ["Bulgária","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Cambodia","KH"],
    ["Camarões","CM"],
    ["Canada","CA"],
    ["Cabo Verde","CV"],
    ["Ilhas Cayman","KY"],
    ["República Centro Africano","CF"],
    ["Chad","TD"],
    ["Chile","CL"],
    ["China","CN"],
    ["Ilha Christmas","CX"],
    ["Cocos (Keeling)","CC"],
    ["Colombia","CO"],
    ["Comores","KM"],
    ["Congo","CG"],
    ["Congo, República Democrática do","CD"],
    ["Ilhas Cook","CK"],
    ["Costa Rica","CR"],
    ["Costa do Marfim","CI"],
    ["Croácia","HR"],
    ["Cuba","CU"],
    ["Curaçao","CW"],
    ["Chipre","CY"],
    ["República Checa","CZ"],
    ["Dinamarca","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["República Dominicana","DO"],
    ["Equador","EC"],
    ["Egipto","EG"],
    ["El Salvador","SV"],
    ["Guiné Equatorial","GQ"],
    ["Eritrea","ER"],
    ["Estónia","EE"],
    ["Etiópia","ET"],
    ["Ilhas Falkland (Malvinas)","FK"],
    ["Ilhas Faroé","FO"],
    ["Fiji","FJ"],
    ["Finlândia","FI"],
    ["France","FR"],
    ["Guiana Francesa","GF"],
    ["Polinésia Francesa","PF"],
    ["Territórios Franceses do Sul","TF"],
    ["Gabão","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Alemanha","DE"],
    ["Gana","GH"],
    ["Gibraltar","GI"],
    ["Grécia","GR"],
    ["Greenland","GL"],
    ["Granada","GD"],
    ["Guadalupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guiné","GN"],
    ["Guiné-Bissau","GW"],
    ["Guiana","GY"],
    ["Haiti","HT"],
    ["Ilha Heard e McDonald Ilhas","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Hungria","HU"],
    ["Islândia","IS"],
    ["Índia","IN"],
    ["Indonésia","ID"],
    ["O Irã, República Islâmica do","IR"],
    ["Iraque","IQ"],
    ["Ireland","IE"],
    ["Isle of Man","IM"],
    ["Israel","IL"],
    ["Itália","IT"],
    ["Jamaica","JM"],
    ["Japão","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Cazaquistão","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Coreia, República Popular Democrática da","KP"],
    ["Coreia do Sul","KR"],
    ["Kuwait","KW"],
    ["Quirguistão","KG"],
    ["Lao República Democrática Popular","LA"],
    ["Letónia","LV"],
    ["Lebanon","LB"],
    ["Lesoto","LS"],
    ["Liberia","LR"],
    ["A Líbia","LY"],
    ["Liechtenstein","LI"],
    ["Lituânia","LT"],
    ["Luxemburgo","LU"],
    ["Macau","MO"],
    ["Macedónia","MK"],
    ["Madagascar","MG"],
    ["Malawi","MW"],
    ["Malásia","MY"],
    ["Maldives","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Ilhas Marshall","MH"],
    ["Martinica","MQ"],
    ["Mauritânia","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["México","MX"],
    ["Micronésia, Estados Federados da","FM"],
    ["Moldávia, República da","MD"],
    ["Monaco","MC"],
    ["Mongólia","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Marrocos","MA"],
    ["Moçambique","MZ"],
    ["Myanmar","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Países Baixos","NL"],
    ["New Caledonia","NC"],
    ["Nova Zelândia","NZ"],
    ["Nicarágua","NI"],
    ["Niger","NE"],
    ["Nigéria","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Ilhas Marianas do Norte","MP"],
    ["Noruega","NO"],
    ["Oman","OM"],
    ["Paquistão","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panama","PA"],
    ["Papua Nova Guiné","PG"],
    ["Paraguai","PY"],
    ["Peru","PE"],
    ["Filipinas","PH"],
    ["Pitcairn","PN"],
    ["Polônia","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Reunion","RE"],
    ["Roménia","RO"],
    ["Federação Russa","RU"],
    ["Ruanda","RW"],
    ["São Bartolomeu","BL"],
    ["Santa Helena e Tristão da Cunha","SH"],
    ["São Cristóvão e Nevis","KN"],
    ["Santa Lúcia","LC"],
    ["Saint Martin (parte francesa)","MF"],
    ["Saint Pierre e Miquelon","PM"],
    ["São Vicente e Granadinas","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["São Tomé e Príncipe","ST"],
    ["Arábia Saudita","SA"],
    ["Senegal","SN"],
    ["Sérvia","RS"],
    ["Seychelles","SC"],
    ["Sierra Leone","SL"],
    ["Singapura","SG"],
    ["Sint Maarten (parte holandesa)","SX"],
    ["Eslováquia","SK"],
    ["Slovenia","SI"],
    ["Ilhas Salomão","SB"],
    ["Somália","SO"],
    ["África do Sul","ZA"],
    ["Geórgia do Sul","GS"],
    ["Sudão do Sul","SS"],
    ["Spain","ES"],
    ["Sri Lanka","LK"],
    ["Sudão","SD"],
    ["Suriname","SR"],
    ["Svalbard e Jan Mayen","SJ"],
    ["Suazilândia","SZ"],
    ["Suécia","SE"],
    ["Suíça","CH"],
    ["Síria","SY"],
    ["Taiwan, Província da China","TW"],
    ["Tajiquistão","TJ"],
    ["Tanzânia, República Unida da","TZ"],
    ["Tailândia","TH"],
    ["Timor-Leste","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad e Tobago","TT"],
    ["Tunísia","TN"],
    ["Turquia","TR"],
    ["Turcomenistão","TM"],
    ["Turks e Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ucrânia","UA"],
    ["United Arab Emirates","AE"],
    ["Reino Unido","GB"],
    ["Estados Unidos","US"],
    ["Estados Unidos Ilhas Menores Distantes","UM"],
    ["Uruguay","UY"],
    ["Usbequistão","UZ"],
    ["Vanuatu","VU"],
    ["Cidade do Vaticano","VA"],
    ["Venezuela, República Bolivariana da","VE"],
    ["Viet Nam","VN"],
    ["Ilhas Virgens Britânicas","VG"],
    ["Ilhas Virgens, fora dos EUA.","VI"],
    ["Wallis e Futuna","WF"],
    ["Sahara Ocidental","EH"],
    ["Yemen","YE"],
    ["Zambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}