Q.Places.countries = [
    ["Afganistan","AF"],
    ["Insulele Aland","AX"],
    ["Albania","AL"],
    ["Algeria","DZ"],
    ["Samoa Americană","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarctica","AQ"],
    ["Antigua și Barbuda","AG"],
    ["Argentina","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Austria","AT"],
    ["Azerbaidjan","AZ"],
    ["Bahamas","BS"],
    ["Bahrain","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Belarus","BY"],
    ["Belgia","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Bolivia, statul Plurinațional de","BO"],
    ["Bonaire, Sint Eustatius și Saba","BQ"],
    ["Bosnia și Herțegovina","BA"],
    ["Botswana","BW"],
    ["Bouvet Island","BV"],
    ["Brazilia","BR"],
    ["Britanic din Oceanul Indian","IO"],
    ["Brunei Darussalam","BN"],
    ["Bulgaria","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Cambodgia","KH"],
    ["Camerun","CM"],
    ["Canada","CA"],
    ["Capul Verde","CV"],
    ["Insulele Cayman","KY"],
    ["Republica Centrală Africană","CF"],
    ["Ciad","TD"],
    ["Chile","CL"],
    ["China","CN"],
    ["Insula Christmas","CX"],
    ["Cocos (Keeling)","CC"],
    ["Columbia","CO"],
    ["Comore","KM"],
    ["Congo","CG"],
    ["Congo, Republica Democratică","CD"],
    ["Insulele Cook","CK"],
    ["Costa Rica","CR"],
    ["Coasta de Fildeș","CI"],
    ["Croatia","HR"],
    ["Cuba","CU"],
    ["Curaçao","CW"],
    ["Cipru","CY"],
    ["Republica Cehă","CZ"],
    ["Danemarca","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Republica Dominicană","DO"],
    ["Ecuador","EC"],
    ["Egipt","EG"],
    ["El Salvador","SV"],
    ["Guineea Ecuatorială","GQ"],
    ["Eritrea","ER"],
    ["Estonia","EE"],
    ["Etiopia","ET"],
    ["Insulele Falkland (Malvine)","FK"],
    ["Insulele Feroe","FO"],
    ["Fiji","FJ"],
    ["Finlanda","FI"],
    ["Franța","FR"],
    ["Guyana Franceză","GF"],
    ["Polinezia Franceză","PF"],
    ["Teritoriile Franceze de Sud","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Germania","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Grecia","GR"],
    ["Groenlanda","GL"],
    ["Grenada","GD"],
    ["Guadelupa","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guineea","GN"],
    ["Guineea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Insula Heard și Insulele McDonald","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Ungaria","HU"],
    ["Islanda","IS"],
    ["India","IN"],
    ["Indonezia","ID"],
    ["Iran, Republica Islamică","IR"],
    ["Irak","IQ"],
    ["Irlanda","IE"],
    ["Insula Man","IM"],
    ["Israel","IL"],
    ["Italia","IT"],
    ["Jamaica","JM"],
    ["Japonia","JP"],
    ["Jersey","JE"],
    ["Iordania","JO"],
    ["Kazahstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Coreea, Republica Populară Democrată","KP"],
    ["Coreea, Republica","KR"],
    ["Kuweit","KW"],
    ["Kârgâzstan","KG"],
    ["Lao Republica Populară Democrată","LA"],
    ["Letonia","LV"],
    ["Liban","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libia","LY"],
    ["Liechtenstein","LI"],
    ["Lituania","LT"],
    ["Luxemburg","LU"],
    ["Macao","MO"],
    ["Macedonia","MK"],
    ["Madagascar","MG"],
    ["Malawi","MW"],
    ["Malaezia","MY"],
    ["Maldive","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Insulele Marshall","MH"],
    ["Martinica","MQ"],
    ["Mauritania","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mexic","MX"],
    ["Micronezia, Statele Federale ale","FM"],
    ["Republica Moldova","MD"],
    ["Monaco","MC"],
    ["Mongolia","MN"],
    ["Muntenegru","ME"],
    ["Montserrat","MS"],
    ["Maroc","MA"],
    ["Mozambic","MZ"],
    ["Myanmar","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Țările de Jos","NL"],
    ["Noua Caledonie","NC"],
    ["Noua Zeelandă","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Insula Norfolk","NF"],
    ["Insulele Mariane de Nord","MP"],
    ["Norvegia","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panama","PA"],
    ["Papua Noua Guinee","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Filipine","PH"],
    ["Pitcairn","PN"],
    ["Polonia","PL"],
    ["Portugalia","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Reunion","RE"],
    ["România","RO"],
    ["Federația Rusă","RU"],
    ["Rwanda","RW"],
    ["Sfântul Bartolomeu","BL"],
    ["Sfânta Elena și Tristan da Cunha","SH"],
    ["Sfântul Kitts și Nevis","KN"],
    ["Sfânta Lucia","LC"],
    ["Saint-Martin (partea franceza)","MF"],
    ["Saint-Pierre și Miquelon","PM"],
    ["Sfântul Vincent și Grenadine","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome și Principe","ST"],
    ["Arabia Saudită","SA"],
    ["Senegal","SN"],
    ["Serbia","RS"],
    ["Seychelles","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (partea olandeza)","SX"],
    ["Slovacia","SK"],
    ["Slovenia","SI"],
    ["Insulele Solomon","SB"],
    ["Somalia","SO"],
    ["Africa de Sud","ZA"],
    ["Georgia de Sud","GS"],
    ["Sudanul de Sud","SS"],
    ["Spania","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Surinam","SR"],
    ["Svalbard și Jan Mayen","SJ"],
    ["Swaziland","SZ"],
    ["Suedia","SE"],
    ["Elveția","CH"],
    ["Republica Arabă Siriană","SY"],
    ["Taiwan, provincia din China","TW"],
    ["Tadjikistan","TJ"],
    ["Tanzania, Republica Unită","TZ"],
    ["Tailanda","TH"],
    ["Timorul de Est","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad-Tobago","TT"],
    ["Tunisia","TN"],
    ["Turcia","TR"],
    ["Turkmenistan","TM"],
    ["Insulele Turks și Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ucraina","UA"],
    ["Emiratele Arabe Unite","AE"],
    ["Marea Britanie","GB"],
    ["Statele Unite ale Americii","US"],
    ["Statele Unite ale Americii Insulele Minore Îndepărtate","UM"],
    ["Uruguay","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Cetatea Vaticanului","VA"],
    ["Venezuela, Republica Bolivariană","VE"],
    ["Vietnam","VN"],
    ["Insulele Virgine Britanice","VG"],
    ["Insulele Virgine, U.S.","VI"],
    ["Wallis și Futuna","WF"],
    ["Sahara Occidentală","EH"],
    ["Yemen","YE"],
    ["Zambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}