Q.Places.countries = [
    ["Afganistan","AF"],
    ["Åland","AX"],
    ["Albanija","AL"],
    ["Alžirija","DZ"],
    ["Ameriška Samoa","AS"],
    ["Andora","AD"],
    ["Angola","AO"],
    ["Angvila","AI"],
    ["Antarktika","AQ"],
    ["Antigva in Barbuda","AG"],
    ["Argentina","AR"],
    ["Armenija","AM"],
    ["Aruba","AW"],
    ["Avstralija","AU"],
    ["Avstrija","AT"],
    ["Azerbajdžan","AZ"],
    ["Bahamas","BS"],
    ["Bahrajn","BH"],
    ["Bangladeš","BD"],
    ["Barbados","BB"],
    ["Belarus","BY"],
    ["Belgija","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermudi","BM"],
    ["Butan","BT"],
    ["Bolivija, večnacionalna država","BO"],
    ["Bonaire, Sint Eustatius in Saba","BQ"],
    ["Bosna in Hercegovina","BA"],
    ["Bocvana","BW"],
    ["Bouvet Island","BV"],
    ["Brazilija","BR"],
    ["Britansko ozemlje Indijskega oceana","IO"],
    ["Brunej","BN"],
    ["Bolgarija","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambodža","KH"],
    ["Kamerun","CM"],
    ["Kanada","CA"],
    ["Zelenortski otoki","CV"],
    ["Kajmanski otoki","KY"],
    ["Srednjeafriška republika","CF"],
    ["Chad","TD"],
    ["Čile","CL"],
    ["Kitajska","CN"],
    ["Božični otok","CX"],
    ["Cocos (Keeling) otoki","CC"],
    ["Kolumbija","CO"],
    ["Komori","KM"],
    ["Kongo","CG"],
    ["Kongo, Demokratična republika","CD"],
    ["Cookovi otoki","CK"],
    ["Costa Rica","CR"],
    ["Slonokoščena obala","CI"],
    ["Hrvaška","HR"],
    ["Kuba","CU"],
    ["Curaçao","CW"],
    ["Ciper","CY"],
    ["Češka","CZ"],
    ["Danska","DK"],
    ["Džibuti","DJ"],
    ["Dominika","DM"],
    ["Dominikanska republika","DO"],
    ["Ekvador","EC"],
    ["Egipt","EG"],
    ["El Salvador","SV"],
    ["Ekvatorialna Gvineja","GQ"],
    ["Eritreja","ER"],
    ["Estonija","EE"],
    ["Etiopija","ET"],
    ["Falklandski otoki (Malvini)","FK"],
    ["Ferski otoki","FO"],
    ["Fidži","FJ"],
    ["Finska","FI"],
    ["Francija","FR"],
    ["Francoska Gvajana","GF"],
    ["Francoska Polinezija","PF"],
    ["Francosko južno ozemlje","TF"],
    ["Gabon","GA"],
    ["Gambija","GM"],
    ["Gruzija","GE"],
    ["Nemčija","DE"],
    ["Gana","GH"],
    ["Gibraltar","GI"],
    ["Grčija","GR"],
    ["Grenlandija","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Gvatemala","GT"],
    ["Guernsey","GG"],
    ["Gvineja","GN"],
    ["Gvineja Bissau","GW"],
    ["Gvajana","GY"],
    ["Haiti","HT"],
    ["Otok Heard in otočje McDonald","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Madžarska","HU"],
    ["Islandija","IS"],
    ["Indija","IN"],
    ["Indonezija","ID"],
    ["Iran, Islamic Republic of","IR"],
    ["Irak","IQ"],
    ["Irska","IE"],
    ["Isle of Man","IM"],
    ["Izrael","IL"],
    ["Italija","IT"],
    ["Jamajka","JM"],
    ["Japonska","JP"],
    ["Jersey","JE"],
    ["Jordanija","JO"],
    ["Kazahstan","KZ"],
    ["Kenija","KE"],
    ["Kiribati","KI"],
    ["Koreja, Demokratična ljudska republika","KP"],
    ["Republika Koreja","KR"],
    ["Kuvajt","KW"],
    ["Kirgizistan","KG"],
    ["Lao ljudska demokratična republika","LA"],
    ["Latvija","LV"],
    ["Libanon","LB"],
    ["Lesoto","LS"],
    ["Liberija","LR"],
    ["Libija","LY"],
    ["Lihtenštajn","LI"],
    ["Litva","LT"],
    ["Luksemburg","LU"],
    ["Macao","MO"],
    ["Makedonija","MK"],
    ["Madagaskar","MG"],
    ["Malavi","MW"],
    ["Malezija","MY"],
    ["Maldivi","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshallovi otoki","MH"],
    ["Martinik","MQ"],
    ["Mavretanija","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mehika","MX"],
    ["Mikronezija, Federativne države","FM"],
    ["Moldova, Republika","MD"],
    ["Monako","MC"],
    ["Mongolija","MN"],
    ["Črna gora","ME"],
    ["Montserrat","MS"],
    ["Maroko","MA"],
    ["Mozambik","MZ"],
    ["Mjanmar","MM"],
    ["Namibija","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Nizozemska","NL"],
    ["Nova Kaledonija","NC"],
    ["Nova Zelandija","NZ"],
    ["Nikaragva","NI"],
    ["Niger","NE"],
    ["Nigerija","NG"],
    ["Niue","NU"],
    ["Norfolk Island","NF"],
    ["Severni Marianski otoki","MP"],
    ["Norveška","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestine","PS"],
    ["Panama","PA"],
    ["Papua Nova Gvineja","PG"],
    ["Paragvaj","PY"],
    ["Peru","PE"],
    ["Filipini","PH"],
    ["Pitcairn","PN"],
    ["Poljska","PL"],
    ["Portugalska","PT"],
    ["Puerto Rico","PR"],
    ["Katar","QA"],
    ["Reunion","RE"],
    ["Romunija","RO"],
    ["Ruska federacija","RU"],
    ["Ruanda","RW"],
    ["Saint Barthelemy","BL"],
    ["Saint Helena in Tristan da Cunha","SH"],
    ["Saint Kitts in Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Sveti Martin (francoski del)","MF"],
    ["Saint Pierre in Miquelon","PM"],
    ["Saint Vincent in Grenadine","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome in Principe","ST"],
    ["Saudova Arabija","SA"],
    ["Senegal","SN"],
    ["Srbija","RS"],
    ["Sejšeli","SC"],
    ["Sierra Leone","SL"],
    ["Singapur","SG"],
    ["Sint Maarten (nizozemski del)","SX"],
    ["Slovaška","SK"],
    ["Slovenija","SI"],
    ["Salomonovi otoki","SB"],
    ["Somalija","SO"],
    ["Južna Afrika","ZA"],
    ["South Georgia","GS"],
    ["South Sudan","SS"],
    ["Španija","ES"],
    ["Šrilanka","LK"],
    ["Sudan","SD"],
    ["Surinam","SR"],
    ["Svalbard in Jan Mayen","SJ"],
    ["Svazi","SZ"],
    ["Švedska","SE"],
    ["Švica","CH"],
    ["Sirska arabska republika","SY"],
    ["Tajvan, Provinca Kitajske","TW"],
    ["Tadžikistan","TJ"],
    ["Tanzanija, Združena republika","TZ"],
    ["Tajska","TH"],
    ["Timor-Leste","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad in Tobago","TT"],
    ["Tunizija","TN"],
    ["Turčija","TR"],
    ["Turkmenistan","TM"],
    ["Turks in Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukrajina","UA"],
    ["Združeni arabski emirati","AE"],
    ["Velika Britanija","GB"],
    ["Združene države Amerike","US"],
    ["Združene države Stranski zunanji otoki","UM"],
    ["Urugvaj","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatikan","VA"],
    ["Venezuela, Bolivarska republika","VE"],
    ["Vietnam","VN"],
    ["Deviški otoki, britanski","VG"],
    ["Deviški otoki, zunaj Združenih držav.","VI"],
    ["Wallis in Futuna","WF"],
    ["Zahodna Sahara","EH"],
    ["Jemen","YE"],
    ["Zambija","ZM"],
    ["Zimbabve","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}