Q.Places.countries = [
    [ "Afganistani", "AF"],
    [ "Aland Islands", "AX"],
    [ "Albania", "AL"],
    [ "Algjeria", "DZ"],
    [ "American Samoa", "AS"],
    [ "Andorra", "AD"],
    [ "Angola", "AO"],
    [ "Anguilla", "AI"],
    [ "Antarctica", "AQ"],
    [ "Antarktidë", "AG"],
    [ "Argentina", "AR"],
    [ "Armenia", "AM"],
    [ "Aruba", "AW"],
    [ "Australia", "AU"],
    [ "Austria", "AT"],
    [ "Azerbajxhani", "AZ"],
    [ "Bahamas", "BS"],
    [ "Bahrain", "BH"],
    [ "Bangladesh", "BD"],
    [ "Barbados", "BB"],
    [ "Belarus", "NGA"],
    [ "Belgjika", "BE"],
    [ "Belize", "BZ"],
    [ "Benin", "BJ"],
    [ "Bermuda", "BM"],
    [ "Bhutan", "BT"],
    [ "Bolivia, State Plurinational e", "BO"],
    [ "Bonaire, Sint Eustatius dhe Saba", "BQ"],
    [ "Bosnja dhe Hercegovina", "BA"],
    [ "Botswana", "BW"],
    [ "Bouvet Island", "BV"],
    [ "Brazil", "BR"],
    [ "Territory British Indian Ocean", "IO"],
    [ "Brunei", "BN"],
    [ "Bulgaria", "BG"],
    [ "Burkina Faso", "BF"],
    [ "Burundi", "BI"],
    [ "Kamboxhia", "KH"],
    [ "Cameroon", "CM"],
    [ "Canada", "CA"],
    [ "Cape Verde", "CV"],
    [ "Ishujt Kajman", "KY"],
    [ "Republika e Afrikës Qendrore", "CF"],
    [ "Chad", "TD"],
    [ "Chile", "CL"],
    [ "China", "CN"],
    [ "Christmas Island", "CX"],
    [ "Cocos (Keeling) Islands", "CC"],
    [ "Kolumbia", "CO"],
    [ "Komoros", "KM"],
    [ "Congo", "CG"],
    [ "Kongo, Republika Demokratike e", "CD"],
    [ "Ishujt Kuk", "CK"],
    [ "Kostarikë", "CR"],
    [ "Côte d'Ivoire", "CI"],
    [ "Kroacia", "HR"],
    [ "Kuba", "CU"],
    [ "Curaçao", "CW"],
    [ "Cyprus", "CY"],
    [ "Republika Çeke", "CZ"],
    [ "Danimarka", "DK"],
    [ "Djibouti", "DJ"],
    [ "Dominica", "DM"],
    [ "Republika Dominikane", "DO"],
    [ "Ecuador", "EC"],
    [ "Egypt", "EG"],
    [ "El Salvador", "SV"],
    [ "Guinea Ekuatoriale", "GQ"],
    [ "Eritrea", "ER"],
    [ "Estonia", "EE"],
    [ "Ethiopia", "ET"],
    [ "Falkland Islands (Malvinas)", "FK"],
    [ "Faroe Islands", "FO"],
    [ "Fiji", "FJ"],
    [ "Finland", "FI"],
    [ "France", "FR"],
    [ "French Guiana", "GSH"],
    [ "Polinezia Franceze", "PF"],
    [ "French Southern Territories", "TF"],
    [ "Gabon", "GA"],
    [ "Gambia", "GM"],
    [ "Gjeorgjia", "GE"],
    [ "Germany", "DE"],
    [ "Ghana", "GH"],
    [ "Gibraltar", "GI"],
    [ "Greqia", "GR"],
    [ "Greenland", "GL"],
    [ "Grenadë", "GD"],
    [ "Guadeloupe", "GP"],
    [ "Guam", "GU"],
    [ "Guatemala", "GT"],
    [ "Guernsey", "GG"],
    [ "Guineja", "GN"],
    [ "Guinea-Bissau", "GW"],
    [ "Guyana", "GY"],
    [ "Haiti", "HT"],
    [ "Heard Island dhe McDonald Islands", "HM"],
    [ "Honduras", "HN"],
    [ "Hong Kong", "HK"],
    [ "Hungaria", "HU"],
    [ "Iceland", "IS"],
    [ "India", "IN"],
    [ "Indonesia", "ID"],
    [ "Iran, Islamic Republika e", "IR"],
    [ "Irak", "IQ"],
    [ "Ireland", "IE"],
    [ "Ishulli i Njeriut", "IM"],
    [ "Israel", "IL"],
    [ "Italia", "IT"],
    [ "Jamaica", "JM"],
    [ "Japonia", "JP"],
    [ "Jersey", "JE"],
    [ "Jordan", "JO"],
    [ "Kazakistani", "KZ"],
    [ "Kenia", "KE"],
    [ "Kiribati", "KI"],
    [ "Korea, Republika Popullore Demokratike e", "PK"],
    [ "Korea, Republic of", "KR"],
    [ "Kuwait", "KW"],
    [ "Kirgistan", "KG"],
    [ "Lao Republika Demokratike Popullore", "LA"],
    [ "Latvia", "LV"],
    [ "Libani", "LB"],
    [ "Lesotho", "LS"],
    [ "Liberia", "LR"],
    [ "Libya", "LY"],
    [ "Liechtenstein", "LI"],
    [ "Lituania", "LT"],
    [ "Luxembourg", "LU"],
    [ "Makao", "MO"],
    [ "Maqedonia", "MK"],
    [ "Madagascar", "MG"],
    [ "Malawi", "MW"],
    [ "Bardhë", "MY"],
    [ "Maldives", "MV"],
    [ "Mali", "ML"],
    [ "Malta", "MT"],
    [ "Ishujt Marshall", "MSH"],
    [ "Martinique", "MQ"],
    [ "Mauritania", "MR"],
    [ "Mauritius", "mu"],
    [ "Mayotte", "YT"],
    [ "Mexico", "MX"],
    [ "Mikronezi, federuar Shtetet e Bashkuara", "FM"],
    [ "Moldova, Republic of", "MD"],
    [ "Monaco", "MC"],
    [ "Mongolia", "MN"],
    [ "Mali i Zi", "ME"],
    [ "Montserrat", "Zonja"],
    [ "Morocco", "MA"],
    [ "Mozambik", "MZ"],
    [ "Myanmar", "MM"],
    [ "Namibia", "NA"],
    [ "Nauru", "NR"],
    [ "Nepal", "NP"],
    [ "Holanda", "NL"],
    [ "Kaledonia e Re", "NC"],
    [ "Zelanda e Re", "NZ"],
    [ "Nicaragua", "NI"],
    [ "Niger", "NE"],
    [ "Nigeria", "NG"],
    [ "Niue", "NU"],
    [ "Niue", "NF"],
    [ "Northern Mariana Islands", "MP"],
    [ "Norvegjia", "JO"],
    [ "Oman", "OM"],
    [ "Pakistan", "PK"],
    [ "Palau", "PW"],
    [ "Palestina", "PS"],
    [ "Panama", "PA"],
    [ "Papua New Guinea", "PG"],
    [ "Paraguay", "PY"],
    [ "Peru", "PE"],
    [ "Philippines", "PH"],
    [ "Pitcairn", "PN"],
    [ "Polonia", "PL"],
    [ "Portugal", "PT"],
    [ "Portoriko", "PR"],
    [ "Qatar", "QA"],
    [ "Réunion", "RE"],
    [ "Rumania", "RO"],
    [ "Federata Ruse", "RU"],
    [ "Ruanda", "RW"],
    [ "Shën Barthélemy", "BL"],
    [ "Saint Helena dhe Tristan da Cunha", "SH"],
    [ "Saint Kitts dhe Nevis", "KN"],
    [ "St Lucia", "LC"],
    [ "Saint Martin (pjesa frëngjisht)", "MF"],
    [ "Shën Pierre dhe Miquelon", "PM"],
    [ "Shën Vincenti dhe Grenadinet", "VC"],
    [ "Samoa", "WS"],
    [ "San Marino", "SM"],
    [ "Sao Tome dhe Principe", "ST"],
    [ "Arabia Saudite", "SA"],
    [ "Senegal", "SN"],
    [ "Serbia", "RS"],
    [ "Seychelles", "SC"],
    [ "Sierra Leone", "SL"],
    [ "Singapor", "SG"],
    [ "Sint Maarten (pjesa holandeze)", "SX"],
    [ "Sllovakia", "SK"],
    [ "Sllovenia", "SI"],
    [ "Ishujt Solomon", "SB"],
    [ "Somalia", "SO"],
    [ "Afrika e Jugut", "ZA"],
    [ "Gjeorgjia Jugore", "GS"],
    [ "South Sudan", "SS"],
    [ "Spain", "ES"],
    [ "Sri Lanka", "LK"],
    [ "Sudan", "SD"],
    [ "Suriname", "SR"],
    [ "Svalbard dhe Jan Mayen", "SJ"],
    [ "Swaziland", "SZ"],
    [ "Suedia", "SE"],
    [ "Switzerland", "CH"],
    [ "Syrian Arab Republic", "SY"],
    [ "Tajvan, Provinca e Kinës", "TW"],
    [ "Taxhikistani", "TJ"],
    [ "Tanzania, United Republic of", "TZ"],
    [ "Thailand", "TH"],
    [ "Timor-Leste", "TL"],
    [ "Togo", "TG"],
    [ "Tokelau", "TK"],
    [ "Tonga", "TO"],
    [ "Trinidad dhe Tobago", "TT"],
    [ "Tunizia", "TN"],
    [ "Turkey", "TR"],
    [ "Turkmenistan", "TM"],
    [ "Turks dhe Caicos Ishujt", "TC"],
    [ "Tuvalu", "TV"],
    [ "Uganda", "UG"],
    [ "Ukrainë", "UA"],
    [ "Emiratet e Bashkuara Arabe", "AE"],
    [ "Mbretëria e Bashkuar", "GB"],
    [ "Shtetet e Bashkuara", "US"],
    [ "Shtetet e Bashkuara Ishujt Minor periferike", "UM"],
    [ "Uruguay", "UY"],
    [ "Uzbekistan", "UZ"],
    [ "Vanuatu", "VU"],
    [ "Vatikani shteti", "VA"],
    [ "Venezuela: Republika e Bolivarian", "VE"],
    [ "Viet Nam", "VN"],
    [ "Virgin Islands, British", "VG"],
    [ "Virgin Islands, U.S.", "VI"],
    [ "Wallis dhe Futuna", "WF"],
    [ "Western Sahara", "EH"],
    [ "Yemen", "YE"],
    [ "Zambia", "ZM"],
    [ "Zimbabwe", "ZW"]
];

Q.Places.countryLookupByCode = {
    "AF": "4",
    "AL": "8",
    "AQ": "10",
    "DZ": "12",
    "AS": "16",
    "AD": "20",
    "AO": "24",
    "AG": "28",
    "AZ": "31",
    "AR": "32",
    "AU": "36",
    "AT": "40",
    "BS": "44",
    "BH": "48",
    "BD": "50",
    "AM": "51",
    "BB": "52",
    "BE": "56",
    "BM": "60",
    "BT": "64",
    "BO": "68",
    "BA": "70",
    "BW": "72",
    "BV": "74",
    "BR": "76",
    "BZ": "84",
    "IO": "86",
    "SB": "90",
    "VG": "92",
    "BN": "96",
    "BG": "100",
    "MM": "104",
    "BI": "108",
    "NGA": "112",
    "KH": "116",
    "CM": "120",
    "CA": "124",
    "CV": "132",
    "KY": "136",
    "CF": "140",
    "LK": "144",
    "TD": "148",
    "CL": "152",
    "CN": "156",
    "TW": "158",
    "CX": "162",
    "CC": "166",
    "CO": "170",
    "KM": "174",
    "YT": "175",
    "CG": "178",
    "CD": "180",
    "CK": "184",
    "CR": "188",
    "HR": "191",
    "CU": "192",
    "CY": "196",
    "CZ": "203",
    "BJ": "204",
    "DK": "208",
    "DM": "212",
    "DO": "214",
    "EC": "218",
    "SV": "222",
    "GQ": "226",
    "ET": "231",
    "ER": "232",
    "EE": "233",
    "FO": "234",
    "FK": "238",
    "GS": "239",
    "FJ": "242",
    "FI": "246",
    "AX": "248",
    "FR": "250",
    "GF": "254",
    "PF": "258",
    "TF": "260",
    "DJ": "262",
    "GA": "266",
    "GE": "268",
    "GM": "270",
    "PS": "275",
    "DE": "276",
    "GH": "288",
    "GI": "292",
    "KI": "296",
    "GR": "300",
    "GL": "304",
    "GD": "308",
    "GP": "312",
    "GU": "316",
    "GT": "320",
    "GN": "324",
    "GY": "328",
    "HT": "332",
    "HM": "334",
    "VA": "336",
    "HN": "340",
    "HK": "344",
    "HU": "348",
    "IS": "352",
    "NE": "356",
    "ID": "360",
    "IR": "364",
    "IQ": "368",
    "IE": "372",
    "IL": "376",
    "IT": "380",
    "CI": "384",
    "JM": "388",
    "JP": "392",
    "KZ": "398",
    "JO": "400",
    "KE": "404",
    "PK": "408",
    "KR": "410",
    "KW": "414",
    "KG": "417",
    "LA": "418",
    "LB": "422",
    "LS": "426",
    "LV": "428",
    "LR": "430",
    "LY": "434",
    "LI": "438",
    "LT": "440",
    "LU": "442",
    "MO": "446",
    "MG": "450",
    "MW": "454",
    "MY": "458",
    "MV": "462",
    "ML": "466",
    "MT": "470",
    "MQ": "474",
    "MR": "478",
    "MU": "480",
    "MX": "484",
    "MC": "492",
    "MN": "496",
    "MD": "498",
    "ME": "499",
    "MS": "500",
    "KK": "504",
    "MZ": "508",
    "OM": "512",
    "NA": "516",
    "NR": "520",
    "NP": "524",
    "NL": "528",
    "CW": "531",
    "AW": "533",
    "SX": "534",
    "BQ": "535",
    "NC": "540",
    "VU": "548",
    "NZ": "554",
    "NI": "558",
    "NE": "562",
    "NG": "566",
    "NU": "570",
    "NF": "574",
    "JO": "578",
    "MP": "580",
    "UM": "581",
    "FM": "583",
    "MH": "584",
    "PW": "585",
    "PK": "586",
    "PA": "591",
    "PG": "598",
    "PY": "600",
    "PE": "604",
    "PH": "608",
    "PN": "612",
    "PL": "616",
    "PT": "620",
    "GW": "624",
    "TL": "626",
    "PR": "630",
    "QA": "634",
    "RE": "638",
    "RO": "642",
    "RU": "643",
    "RW": "646",
    "BL": "652",
    "SH": "654",
    "KN": "659",
    "AI": "660",
    "LC": "662",
    "MF": "663",
    "PM": "666",
    "VC": "670",
    "SM": "674",
    "ST": "678",
    "SA": "682",
    "SN": "686",
    "RS": "688",
    "SC": "690",
    "SL": "694",
    "SG": "702",
    "SK": "703",
    "VN": "704",
    "SI": "705",
    "SO": "706",
    "ZA": "710",
    "ZW": "716",
    "ES": "724",
    "SS": "728",
    "SD": "729",
    "EH": "732",
    "SR": "740",
    "SJ": "744",
    "SZ": "748",
    "SE": "752",
    "CH": "756",
    "SY": "760",
    "TJ": "762",
    "TH": "764",
    "TG": "768",
    "TK": "772",
    "TO": "776",
    "TT": "780",
    "AE": "784",
    "TN": "788",
    "TR": "792",
    "TM": "795",
    "TC": "796",
    "TV": "798",
    "UG": "800",
    "UA": "804",
    "MK": "807",
    "EG": "818",
    "GB": "826",
    "GG": "831",
    "JE": "832",
    "IM": "833",
    "TZ": "834",
    "US": "840",
    "VI": "850",
    "BF": "854",
    "UY": "858",
    "UZ": "860",
    "VE": "862",
    "WF": "876",
    "WS": "882",
    "YE": "887",
    "ZM": "894"
}