Q.Places.countries = [
    ["Afghanistan","AF"],
    ["Åland","AX"],
    ["Albania","AL"],
    ["Algeriet","DZ"],
    ["Amerikanska Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Antarktis","AQ"],
    ["Antigua och Barbuda","AG"],
    ["Argentina","AR"],
    ["Armenien","AM"],
    ["Aruba","AW"],
    ["Australien","AU"],
    ["Österrike","AT"],
    ["Azerbajdzjan","AZ"],
    ["Bahamas","BS"],
    ["Bahrain","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Vitryssland","BY"],
    ["Belgien","BE"],
    ["Belize","BZ"],
    ["Benin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Bolivia, Mångnationella staten","BO"],
    ["Bonaire, Sint Eustatius och Saba","BQ"],
    ["Bosnien och Hercegovina","BA"],
    ["Botswana","BW"],
    ["Bouvetön","BV"],
    ["Brasilien","BR"],
    ["Brittiska territoriet i Indiska oceanen","IO"],
    ["Brunei","BN"],
    ["Bulgarien","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Kambodja","KH"],
    ["Kamerun","CM"],
    ["Canada","CA"],
    ["Kap Verde","CV"],
    ["Caymanöarna","KY"],
    ["Centralafrikanska republiken","CF"],
    ["Chad","TD"],
    ["Chile","CL"],
    ["Kina","CN"],
    ["Julön","CX"],
    ["Cocos (Keeling) Islands","CC"],
    ["Colombia","CO"],
    ["Komorerna","KM"],
    ["Kongo","CG"],
    ["Kongo, Demokratiska republiken","CD"],
    ["Cooköarna","CK"],
    ["Costa Rica","CR"],
    ["Elfenbenskusten","CI"],
    ["Kroatien","HR"],
    ["Kuba","CU"],
    ["Curaçao","CW"],
    ["Cypern","CY"],
    ["Tjeckien","CZ"],
    ["Danmark","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Dominikanska republiken","DO"],
    ["Ecuador","EC"],
    ["Egypten","EG"],
    ["El Salvador","SV"],
    ["Ekvatorialguinea","GQ"],
    ["Eritrea","ER"],
    ["Estland","EE"],
    ["Etiopien","ET"],
    ["Falkland Islands (Malvinas)","FK"],
    ["Färöarna","FO"],
    ["Fiji","FJ"],
    ["Finland","FI"],
    ["Frankrike","FR"],
    ["Franska Guyana","GF"],
    ["Franska Polynesien","PF"],
    ["Franska Sydterritorierna","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Tyskland","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Grekland","GR"],
    ["Grönland","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Heard Island och McDonald öar","HM"],
    ["Honduras","HN"],
    ["Hong Kong","HK"],
    ["Ungern","HU"],
    ["Island","IS"],
    ["Indien","IN"],
    ["Indonesien","ID"],
    ["Iran, Islamic Republic of","IR"],
    ["Irak","IQ"],
    ["Irland","IE"],
    ["Isle of Man","IM"],
    ["Israel","IL"],
    ["Italien","IT"],
    ["Jamaica","JM"],
    ["Japan","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazakstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Korea, Demokratiska folkrepubliken","KP"],
    ["Sydkorea","KR"],
    ["Kuwait","KW"],
    ["Kirgizistan","KG"],
    ["Lao Demokratiska folkrepubliken","LA"],
    ["Lettland","LV"],
    ["Libanon","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libyen","LY"],
    ["Liechtenstein","LI"],
    ["Litauen","LT"],
    ["Luxemburg","LU"],
    ["Macao","MO"],
    ["Makedonien","MK"],
    ["Madagaskar","MG"],
    ["Malawi","MW"],
    ["Malaysia","MY"],
    ["Maldiverna","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Marshallöarna","MH"],
    ["Martinique","MQ"],
    ["Mauretanien","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mexico","MX"],
    ["Mikronesien, federationen","FM"],
    ["Moldavien","MD"],
    ["Monaco","MC"],
    ["Mongoliet","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Marocko","MA"],
    ["Moçambique","MZ"],
    ["Burma","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Nederländerna","NL"],
    ["New Caledonia","NC"],
    ["Nya Zeeland","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Norfolkön","NF"],
    ["Nordmarianerna","MP"],
    ["Norge","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestina","PS"],
    ["Panama","PA"],
    ["Papua Nya Guinea","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Filippinerna","PH"],
    ["Pitcairn","PN"],
    ["Polen","PL"],
    ["Portugal","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Réunion","RE"],
    ["Rumänien","RO"],
    ["Ryssland","RU"],
    ["Rwanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena och Tristan da Cunha","SH"],
    ["Saint Kitts och Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (franska delen)","MF"],
    ["Saint Pierre och Miquelon","PM"],
    ["Saint Vincent och Grenadinerna","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tomé och Principe","ST"],
    ["Saudiarabien","SA"],
    ["Senegal","SN"],
    ["Serbien","RS"],
    ["Seychellerna","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (nederländska delen)","SX"],
    ["Slovakien","SK"],
    ["Slovenien","SI"],
    ["Salomonöarna","SB"],
    ["Somalia","SO"],
    ["South Africa","ZA"],
    ["Sydgeorgien","GS"],
    ["Södra Sudan","SS"],
    ["Spanien","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Surinam","SR"],
    ["Svalbard och Jan Mayen","SJ"],
    ["Swaziland","SZ"],
    ["Sverige","SE"],
    ["Schweiz","CH"],
    ["Syrien","SY"],
    ["Taiwan, provinsen i Kina","TW"],
    ["Tadzjikistan","TJ"],
    ["Tanzania, Förenade republiken","TZ"],
    ["Thailand","TH"],
    ["Östtimor","TL"],
    ["Togo","TG"],
    ["Tokelauöarna","TK"],
    ["Tonga","TO"],
    ["Trinidad och Tobago","TT"],
    ["Tunisien","TN"],
    ["Turkiet","TR"],
    ["Turkmenistan","TM"],
    ["Turks- och Caicosöarna","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraina","UA"],
    ["Förenade Arabemiraten","AE"],
    ["Storbritannien","GB"],
    ["United States","US"],
    ["Förenta staternas avlägset belägna öar","UM"],
    ["Uruguay","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatikanstaten","VA"],
    ["Venezuela, Bolivarianska republiken","VE"],
    ["Viet Nam","VN"],
    ["Brittiska Jungfruöarna","VG"],
    ["Jungfruöarna, US.","VI"],
    ["Wallis och Futuna","WF"],
    ["Västsahara","EH"],
    ["Jemen","YE"],
    ["Zambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}