Q.Places.countries = [
    ["Afghanistan","AF"],
    ["Åland Islands","AX"],
    ["Albania","AL"],
    ["Algeria","DZ"],
    ["American Samoa","AS"],
    ["Andorra","AD"],
    ["Angola","AO"],
    ["Anguilla","AI"],
    ["Nam Cực","AQ"],
    ["Antigua và Barbuda","AG"],
    ["Argentina","AR"],
    ["Armenia","AM"],
    ["Aruba","AW"],
    ["Australia","AU"],
    ["Áo","AT"],
    ["Azerbaijan","AZ"],
    ["Bahamas","BS"],
    ["Bahrain","BH"],
    ["Bangladesh","BD"],
    ["Barbados","BB"],
    ["Belarus","BY"],
    ["Bỉ","BE"],
    ["Belize","BZ"],
    ["Bénin","BJ"],
    ["Bermuda","BM"],
    ["Bhutan","BT"],
    ["Cộng hòa Bolivia của","BO"],
    ["Bonaire, Sint Eustatius và Saba","BQ"],
    ["Bosnia và Herzegovina","BA"],
    ["Botswana","BW"],
    ["Bouvet Island","BV"],
    ["Brazil","BR"],
    ["British Indian Ocean Territory","IO"],
    ["Brunei Darussalam","BN"],
    ["Bulgaria","BG"],
    ["Burkina Faso","BF"],
    ["Burundi","BI"],
    ["Campuchia","KH"],
    ["Cameroon","CM"],
    ["Canada","CA"],
    ["Cape Verde","CV"],
    ["Quần đảo Cayman","KY"],
    ["Cộng hòa Trung Phi","CF"],
    ["Chad","TD"],
    ["Chile","CL"],
    ["Trung Quốc","CN"],
    ["Đảo Christmas","CX"],
    ["Quần đảo Cocos (Keeling) Quần đảo","CC"],
    ["Colombia","CO"],
    ["Comoros","KM"],
    ["Congo","CG"],
    ["Congo, Cộng hòa Dân chủ","CD"],
    ["Quần đảo Cook","CK"],
    ["Costa Rica","CR"],
    ["Côte d'Ivoire","CI"],
    ["Croatia","HR"],
    ["Cuba","CU"],
    ["Curaçao","CW"],
    ["Síp","CY"],
    ["Cộng hòa Séc","CZ"],
    ["Đan Mạch","DK"],
    ["Djibouti","DJ"],
    ["Dominica","DM"],
    ["Cộng hòa Dominica","DO"],
    ["Ecuador","EC"],
    ["Ai Cập","EG"],
    ["El Salvador","SV"],
    ["Equatorial Guinea","GQ"],
    ["Eritrea","ER"],
    ["Estonia","EE"],
    ["Ethiopia","ET"],
    ["Quần đảo Falkland (Malvinas)","FK"],
    ["Faroe Islands","FO"],
    ["Fiji","FJ"],
    ["Phần Lan","FI"],
    ["Pháp","FR"],
    ["Guiana thuộc Pháp","GF"],
    ["French Polynesia","PF"],
    ["Pháp lãnh thổ phía Nam","TF"],
    ["Gabon","GA"],
    ["Gambia","GM"],
    ["Georgia","GE"],
    ["Đức","DE"],
    ["Ghana","GH"],
    ["Gibraltar","GI"],
    ["Hy Lạp","GR"],
    ["Greenland","GL"],
    ["Grenada","GD"],
    ["Guadeloupe","GP"],
    ["Guam","GU"],
    ["Guatemala","GT"],
    ["Guernsey","GG"],
    ["Guinea","GN"],
    ["Guinea-Bissau","GW"],
    ["Guyana","GY"],
    ["Haiti","HT"],
    ["Đảo Heard và quần đảo McDonald","HM"],
    ["Honduras","HN"],
    ["Hồng Kông","HK"],
    ["Hungary","HU"],
    ["Iceland","IS"],
    ["Ấn Độ","IN"],
    ["Indonesia","ID"],
    ["Iran, Cộng hòa Hồi giáo","IR"],
    ["Iraq","IQ"],
    ["Ireland","IE"],
    ["Isle of Man","IM"],
    ["Israel","IL"],
    ["Ý","IT"],
    ["Jamaica","JM"],
    ["Nhật Bản","JP"],
    ["Jersey","JE"],
    ["Jordan","JO"],
    ["Kazakhstan","KZ"],
    ["Kenya","KE"],
    ["Kiribati","KI"],
    ["Hàn Quốc, Cộng hòa dân chủ nhân dân","KP"],
    ["Cộng hòa Hàn Quốc","KR"],
    ["Kuwait","KW"],
    ["Kyrgyzstan","KG"],
    ["CHDCND Lào nhân dân","LA"],
    ["Latvia","LV"],
    ["Lebanon","LB"],
    ["Lesotho","LS"],
    ["Liberia","LR"],
    ["Libya","LY"],
    ["Liechtenstein","LI"],
    ["Lithuania","LT"],
    ["Luxembourg","LU"],
    ["Macao","MO"],
    ["Macedonia","MK"],
    ["Madagascar","MG"],
    ["Malawi","MW"],
    ["Malaysia","MY"],
    ["Maldives","MV"],
    ["Mali","ML"],
    ["Malta","MT"],
    ["Quần đảo Marshall","MH"],
    ["Martinique","MQ"],
    ["Mauritania","MR"],
    ["Mauritius","MU"],
    ["Mayotte","YT"],
    ["Mexico","MX"],
    ["Micronesia, Liên bang","FM"],
    ["Cộng hòa Moldova","MD"],
    ["Monaco","MC"],
    ["Mông Cổ","MN"],
    ["Montenegro","ME"],
    ["Montserrat","MS"],
    ["Morocco","MA"],
    ["Mozambique","MZ"],
    ["Myanmar","MM"],
    ["Namibia","NA"],
    ["Nauru","NR"],
    ["Nepal","NP"],
    ["Hà Lan","NL"],
    ["New Caledonia","NC"],
    ["New Zealand","NZ"],
    ["Nicaragua","NI"],
    ["Niger","NE"],
    ["Nigeria","NG"],
    ["Niue","NU"],
    ["Đảo Norfolk","NF"],
    ["Quần đảo Bắc Mariana","MP"],
    ["Na Uy","NO"],
    ["Oman","OM"],
    ["Pakistan","PK"],
    ["Palau","PW"],
    ["Palestine","PS"],
    ["Panama","PA"],
    ["Papua New Guinea","PG"],
    ["Paraguay","PY"],
    ["Peru","PE"],
    ["Philippines","PH"],
    ["Pitcairn","PN"],
    ["Ba Lan","PL"],
    ["Bồ Đào Nha","PT"],
    ["Puerto Rico","PR"],
    ["Qatar","QA"],
    ["Réunion","RE"],
    ["Romania","RO"],
    ["Liên bang Nga","RU"],
    ["Rwanda","RW"],
    ["Saint Barthélemy","BL"],
    ["Saint Helena và Tristan da Cunha","SH"],
    ["Saint Kitts và Nevis","KN"],
    ["Saint Lucia","LC"],
    ["Saint Martin (tiếng Pháp)","MF"],
    ["Saint Pierre và Miquelon","PM"],
    ["Saint Vincent và Grenadines","VC"],
    ["Samoa","WS"],
    ["San Marino","SM"],
    ["Sao Tome và Principe","ST"],
    ["Ả Rập Saudi","SA"],
    ["Senegal","SN"],
    ["Serbia","RS"],
    ["Seychelles","SC"],
    ["Sierra Leone","SL"],
    ["Singapore","SG"],
    ["Sint Maarten (phần Hà Lan)","SX"],
    ["Slovakia","SK"],
    ["Slovenia","SI"],
    ["Quần đảo Solomon","SB"],
    ["Somalia","SO"],
    ["Nam Phi","ZA"],
    ["South Georgia","GS"],
    ["Nam Sudan","SS"],
    ["Tây Ban Nha","ES"],
    ["Sri Lanka","LK"],
    ["Sudan","SD"],
    ["Suriname","SR"],
    ["Svalbard và Jan Mayen","SJ"],
    ["Swaziland","SZ"],
    ["Thụy Điển","SE"],
    ["Thụy Sĩ","CH"],
    ["Syria","SY"],
    ["Đài Loan, tỉnh của Trung Quốc","TW"],
    ["Tajikistan","TJ"],
    ["Tanzania, Cộng hòa","TZ"],
    ["Thái Lan","TH"],
    ["Timor-Leste","TL"],
    ["Togo","TG"],
    ["Tokelau","TK"],
    ["Tonga","TO"],
    ["Trinidad và Tobago","TT"],
    ["Tunisia","TN"],
    ["Thổ Nhĩ Kỳ","TR"],
    ["Turkmenistan","TM"],
    ["Quần đảo Turks và Caicos","TC"],
    ["Tuvalu","TV"],
    ["Uganda","UG"],
    ["Ukraine","UA"],
    ["United Arab Emirates","AE"],
    ["Vương quốc Anh","GB"],
    ["Hoa Kỳ","US"],
    ["Hoa Kỳ Quần đảo nhỏ xa xôi hẻo lánh","UM"],
    ["Uruguay","UY"],
    ["Uzbekistan","UZ"],
    ["Vanuatu","VU"],
    ["Vatican City State","VA"],
    ["Venezuela, Bolivia Cộng hòa","VE"],
    ["Việt Nam","VN"],
    ["Quần đảo Virgin, Anh","VG"],
    ["Quần đảo Virgin, thuộc Hoa Kỳ.","VI"],
    ["Wallis và Futuna","WF"],
    ["Tây Sahara","EH"],
    ["Yemen","YE"],
    ["Zambia","ZM"],
    ["Zimbabwe","ZW"]
];

Q.Places.countryLookupByCode = {
"AF": "4",
"AL": "8",
"AQ": "10",
"DZ": "12",
"AS": "16",
"AD": "20",
"AO": "24",
"AG": "28",
"AZ": "31",
"AR": "32",
"AU": "36",
"AT": "40",
"BS": "44",
"BH": "48",
"BD": "50",
"AM": "51",
"BB": "52",
"BE": "56",
"BM": "60",
"BT": "64",
"BO": "68",
"BA": "70",
"BW": "72",
"BV": "74",
"BR": "76",
"BZ": "84",
"IO": "86",
"SB": "90",
"VG": "92",
"BN": "96",
"BG": "100",
"MM": "104",
"BI": "108",
"BY": "112",
"KH": "116",
"CM": "120",
"CA": "124",
"CV": "132",
"KY": "136",
"CF": "140",
"LK": "144",
"TD": "148",
"CL": "152",
"CN": "156",
"TW": "158",
"CX": "162",
"CC": "166",
"CO": "170",
"KM": "174",
"YT": "175",
"CG": "178",
"CD": "180",
"CK": "184",
"CR": "188",
"HR": "191",
"CU": "192",
"CY": "196",
"CZ": "203",
"BJ": "204",
"DK": "208",
"DM": "212",
"DO": "214",
"EC": "218",
"SV": "222",
"GQ": "226",
"ET": "231",
"ER": "232",
"EE": "233",
"FO": "234",
"FK": "238",
"GS": "239",
"FJ": "242",
"FI": "246",
"AX": "248",
"FR": "250",
"GF": "254",
"PF": "258",
"TF": "260",
"DJ": "262",
"GA": "266",
"GE": "268",
"GM": "270",
"PS": "275",
"DE": "276",
"GH": "288",
"GI": "292",
"KI": "296",
"GR": "300",
"GL": "304",
"GD": "308",
"GP": "312",
"GU": "316",
"GT": "320",
"GN": "324",
"GY": "328",
"HT": "332",
"HM": "334",
"VA": "336",
"HN": "340",
"HK": "344",
"HU": "348",
"IS": "352",
"IN": "356",
"ID": "360",
"IR": "364",
"IQ": "368",
"IE": "372",
"IL": "376",
"IT": "380",
"CI": "384",
"JM": "388",
"JP": "392",
"KZ": "398",
"JO": "400",
"KE": "404",
"KP": "408",
"KR": "410",
"KW": "414",
"KG": "417",
"LA": "418",
"LB": "422",
"LS": "426",
"LV": "428",
"LR": "430",
"LY": "434",
"LI": "438",
"LT": "440",
"LU": "442",
"MO": "446",
"MG": "450",
"MW": "454",
"MY": "458",
"MV": "462",
"ML": "466",
"MT": "470",
"MQ": "474",
"MR": "478",
"MU": "480",
"MX": "484",
"MC": "492",
"MN": "496",
"MD": "498",
"ME": "499",
"MS": "500",
"MA": "504",
"MZ": "508",
"OM": "512",
"NA": "516",
"NR": "520",
"NP": "524",
"NL": "528",
"CW": "531",
"AW": "533",
"SX": "534",
"BQ": "535",
"NC": "540",
"VU": "548",
"NZ": "554",
"NI": "558",
"NE": "562",
"NG": "566",
"NU": "570",
"NF": "574",
"NO": "578",
"MP": "580",
"UM": "581",
"FM": "583",
"MH": "584",
"PW": "585",
"PK": "586",
"PA": "591",
"PG": "598",
"PY": "600",
"PE": "604",
"PH": "608",
"PN": "612",
"PL": "616",
"PT": "620",
"GW": "624",
"TL": "626",
"PR": "630",
"QA": "634",
"RE": "638",
"RO": "642",
"RU": "643",
"RW": "646",
"BL": "652",
"SH": "654",
"KN": "659",
"AI": "660",
"LC": "662",
"MF": "663",
"PM": "666",
"VC": "670",
"SM": "674",
"ST": "678",
"SA": "682",
"SN": "686",
"RS": "688",
"SC": "690",
"SL": "694",
"SG": "702",
"SK": "703",
"VN": "704",
"SI": "705",
"SO": "706",
"ZA": "710",
"ZW": "716",
"ES": "724",
"SS": "728",
"SD": "729",
"EH": "732",
"SR": "740",
"SJ": "744",
"SZ": "748",
"SE": "752",
"CH": "756",
"SY": "760",
"TJ": "762",
"TH": "764",
"TG": "768",
"TK": "772",
"TO": "776",
"TT": "780",
"AE": "784",
"TN": "788",
"TR": "792",
"TM": "795",
"TC": "796",
"TV": "798",
"UG": "800",
"UA": "804",
"MK": "807",
"EG": "818",
"GB": "826",
"GG": "831",
"JE": "832",
"IM": "833",
"TZ": "834",
"US": "840",
"VI": "850",
"BF": "854",
"UY": "858",
"UZ": "860",
"VE": "862",
"WF": "876",
"WS": "882",
"YE": "887",
"ZM": "894"
}